"""
Sentinel_141 — Level 1 Pulse Sweep + Four Paths Protocol
(TITANOS_SENTINEL_141.md, "Continuous Repository Observation + Four Paths").

WHAT THIS FILE IS, AND IS NOT

A sensor, not a second autonomous builder. Every function in this module
is read-only with respect to the repository: it inspects files and
returns data. **Nothing here writes, deletes, builds, or executes** —
that boundary is a structural fact, not a documented promise, and
`TestSentinelCannotExecute` below checks it by enumerating this module's
public callables.

WHAT WAS AUDITED BEFORE BUILDING

No monitoring, queue producer, health-report generator, or scheduled
sweep exists anywhere in this repository — `PARETO_FRONTIER.md`/
`NEXT_MOVE.md`/`BUILD_REPORT.md` are all hand-maintained prose, updated
manually each cycle, never generated by a deterministic check. No
scheduler exists (no GitHub remote — same standing fact as
`PARETO_FRONTIER.md` FRONTIER-003), so this module implements only
Level 1 (Pulse Sweep) — deterministic, cheap, no model-based review —
and leaves Level 2 (Deep Sweep, semantic) and Level 3 (Strategic
Compaction Review) as doctrine, not code, per the source directive's own
"use model-based review only for semantic questions deterministic code
cannot answer" instruction. Building Level 2/3 as code now, with no
Level 1 in production use yet to prove the pattern, would be exactly the
"busiest system" the source directive's own Final Doctrine warns
against.

WHY THE CHECKS CHOSEN ARE THE ONES CHOSEN

Each of the four `check_*` functions below was picked because running it
against the real repository (not a synthetic fixture) found something
true: `check_claude_md_imports` confirms every `@`-import target exists
(currently: yes); `check_subsystem_build_reports` finds three real
subsystems (`schema/`, `firewall/`, `narrative/`) with no `BUILD_REPORT.md`
at all, unlike their five siblings; `check_python_syntax` is a zero-cost
correctness net; `check_duplicate_frontier_ids` guards the one append-only
registry (`PARETO_FRONTIER.md`) this repo already relies on humans to
keep internally consistent by hand.

CT_141 COMPACTION

`pulse_sweep()` applies the source directive's CT_141 rule directly: if
raw finding count exceeds `COMPACTION_THRESHOLD`, the report is
compacted into a summary (`compacted=True`, `findings` truncated to the
highest-confidence subset) rather than dumping every finding — "never
respond to overwhelm by generating more unverified work."
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

__all__ = [
    "Finding",
    "HealthReport",
    "PathProposal",
    "FourPaths",
    "pulse_sweep",
    "consolidate",
    "format_four_paths",
    "SUBSYSTEMS_REQUIRING_BUILD_REPORT",
    "COMPACTION_THRESHOLD",
]

CONFIDENCE_VALUES = frozenset({"HIGH", "MEDIUM", "LOW"})

# Subsystems this repo's own doctrine (CLAUDE.md "Standing facts") names
# as requiring a BUILD_REPORT.md. Fixed list, not auto-discovered — a
# directory becomes a "subsystem" by human decision, not by having a
# tests/ folder, so this check does not try to infer that decision.
SUBSYSTEMS_REQUIRING_BUILD_REPORT: tuple[str, ...] = (
    "schema", "firewall", "kpm", "magl", "rpa", "taal", "foundation", "narrative",
)

# CT_141: above this many raw findings in one sweep, compact rather than
# dump — deliberately small, this is a Level 1 sweep, not an incident report.
COMPACTION_THRESHOLD = 20

_EXCLUDED_DIRS = {".git", "__pycache__", "node_modules"}


@dataclass(frozen=True)
class Finding:
    """One Level-1 observation. `finding does not equal authorization` —
    nothing about a Finding's shape implies permission to act on it."""

    observation: str
    evidence_location: str
    confidence: str
    interpretation: str
    reversibility: str
    recommended_next_action: str

    def __post_init__(self) -> None:
        if self.confidence not in CONFIDENCE_VALUES:
            raise ValueError(
                f"confidence {self.confidence!r} must be one of {sorted(CONFIDENCE_VALUES)}"
            )
        if not self.evidence_location:
            raise ValueError(
                "a Finding requires evidence_location — a finding with no "
                "location is an opinion, not an observation."
            )

    def key(self) -> tuple[str, str]:
        """Identity used for deduplication: same observation at same location."""
        return (self.observation, self.evidence_location)


@dataclass(frozen=True)
class HealthReport:
    findings: tuple[Finding, ...]
    raw_finding_count: int
    compacted: bool


def consolidate(findings: list[Finding]) -> tuple[Finding, ...]:
    """Deduplicate findings sharing (observation, evidence_location).

    First occurrence wins — later duplicates carry no new location, so
    there is nothing to merge beyond dropping the repeat.
    """
    seen: dict[tuple[str, str], Finding] = {}
    for f in findings:
        seen.setdefault(f.key(), f)
    return tuple(seen.values())


def check_claude_md_imports(repo_root: Path) -> list[Finding]:
    claude_md = repo_root / "CLAUDE.md"
    if not claude_md.exists():
        return [Finding(
            observation="CLAUDE.md is missing",
            evidence_location=str(claude_md),
            confidence="HIGH",
            interpretation="boot configuration is entirely absent",
            reversibility="reversible — file can be restored from git history",
            recommended_next_action="HUMAN_REVIEW_REQUIRED",
        )]
    findings: list[Finding] = []
    for line in claude_md.read_text().splitlines():
        line = line.strip()
        if not line.startswith("@"):
            continue
        target = repo_root / line[1:]
        if not target.exists():
            findings.append(Finding(
                observation=f"CLAUDE.md @-imports a missing file: {line}",
                evidence_location=str(claude_md),
                confidence="HIGH",
                interpretation="doctrine index references a file that does not exist",
                reversibility="reversible — fix the reference or restore the file",
                recommended_next_action="DEFERRED_WITH_NEXT_ACTION: verify and repair the import",
            ))
    return findings


def check_subsystem_build_reports(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for name in SUBSYSTEMS_REQUIRING_BUILD_REPORT:
        subsystem_dir = repo_root / name
        if not subsystem_dir.is_dir():
            continue
        if not (subsystem_dir / "BUILD_REPORT.md").exists():
            findings.append(Finding(
                observation=f"subsystem '{name}' has no BUILD_REPORT.md",
                evidence_location=str(subsystem_dir),
                confidence="MEDIUM",
                interpretation=(
                    "every sibling subsystem carries a BUILD_REPORT.md with "
                    "limitations/human-decisions/next-work-cell sections; "
                    "this one does not, which may mean the audit trail for "
                    "this subsystem lives only in commit messages"
                ),
                reversibility="fully reversible — adding a document has no side effects",
                recommended_next_action="candidate for PARETO_FRONTIER.md, not auto-created",
            ))
    return findings


def check_python_syntax(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in repo_root.rglob("*.py"):
        if any(part in _EXCLUDED_DIRS for part in path.parts):
            continue
        try:
            ast.parse(path.read_text(), filename=str(path))
        except SyntaxError as exc:
            findings.append(Finding(
                observation=f"syntax error: {exc.msg}",
                evidence_location=f"{path}:{exc.lineno}",
                confidence="HIGH",
                interpretation="file cannot be parsed by Python",
                reversibility="reversible — a syntax error blocks nothing until imported",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
    return findings


def check_duplicate_frontier_ids(repo_root: Path) -> list[Finding]:
    frontier_md = repo_root / "PARETO_FRONTIER.md"
    if not frontier_md.exists():
        return []
    ids = re.findall(r"^### (FRONTIER-\S+)", frontier_md.read_text(), flags=re.MULTILINE)
    seen: set[str] = set()
    findings: list[Finding] = []
    for frontier_id in ids:
        if frontier_id in seen:
            findings.append(Finding(
                observation=f"duplicate frontier id: {frontier_id}",
                evidence_location=str(frontier_md),
                confidence="HIGH",
                interpretation="the same candidate id was used twice, risking confused status tracking",
                reversibility="reversible — rename one entry",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
        seen.add(frontier_id)
    return findings


def pulse_sweep(repo_root: Path) -> HealthReport:
    """Run every Level-1 deterministic check and return a consolidated,
    CT_141-compacted HealthReport. Read-only: touches nothing on disk."""
    raw: list[Finding] = []
    raw.extend(check_claude_md_imports(repo_root))
    raw.extend(check_subsystem_build_reports(repo_root))
    raw.extend(check_python_syntax(repo_root))
    raw.extend(check_duplicate_frontier_ids(repo_root))

    consolidated = consolidate(raw)
    raw_count = len(consolidated)

    if raw_count > COMPACTION_THRESHOLD:
        # CT_141: overwhelm is answered by reducing scope, not by
        # generating more unverified work — keep only the highest-
        # confidence findings, in original order.
        order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        compacted_findings = tuple(
            sorted(consolidated, key=lambda f: order[f.confidence])[:COMPACTION_THRESHOLD]
        )
        return HealthReport(findings=compacted_findings, raw_finding_count=raw_count, compacted=True)

    return HealthReport(findings=consolidated, raw_finding_count=raw_count, compacted=False)


@dataclass(frozen=True)
class PathProposal:
    """One of the Four Paths' bounded output structure. Never fabricated —
    absence (None) is the honest alternative, not a filled-in guess."""

    name: str
    purpose: str
    why_now: str
    expected_benefit: str
    cost: str
    evidence: str
    scope: str
    success_criteria: str
    stop_condition: str


@dataclass(frozen=True)
class FourPaths:
    lever: Optional[PathProposal]
    foundation: Optional[PathProposal]
    reality: Optional[PathProposal]
    compaction: Optional[PathProposal]
    recommended: Optional[str] = None  # one of "LEVER"/"FOUNDATION"/"REALITY"/"COMPACTION"
    why_this_one: str = ""

    def __post_init__(self) -> None:
        if self.recommended is not None:
            slot = {
                "LEVER": self.lever, "FOUNDATION": self.foundation,
                "REALITY": self.reality, "COMPACTION": self.compaction,
            }[self.recommended]
            if slot is None:
                raise ValueError(
                    f"cannot recommend {self.recommended!r} — that path has "
                    f"no proposal (would be recommending fabricated work)"
                )


def format_four_paths(paths: FourPaths) -> str:
    """Render the exact end-of-cycle output block the source directive requires."""
    def render(label: str, proposal: Optional[PathProposal]) -> str:
        if proposal is None:
            return f"PATH {label}\nNO STRONG PATH IDENTIFIED\n"
        return (
            f"PATH {label}\n{proposal.purpose}\n\n"
            f"WHY:\n{proposal.why_now}\n"
        )

    lines = [
        "=" * 78,
        "FOUR PATHS OF EVOLUTION",
        "=" * 78,
        "",
        render("1 — LEVER", paths.lever),
        render("2 — FOUNDATION", paths.foundation),
        render("3 — REALITY", paths.reality),
        render("4 — COMPACTION", paths.compaction),
        "RECOMMENDED NEXT MOVE:",
        f"    {paths.recommended or 'NONE'}",
        "",
        "WHY THIS ONE:",
        f"    {paths.why_this_one or 'n/a'}",
    ]
    return "\n".join(lines)
