"""
Sentinel_141 — Level 1 Pulse Sweep + Four Paths Protocol
(TITANOS_SENTINEL_141.md, "Continuous Repository Observation + Four Paths").

WHAT THIS FILE IS, AND IS NOT

A sensor, not a second autonomous builder. Every function in this module
is read-only with respect to the repository: it inspects files and
returns data. **Nothing here writes, deletes, builds, or executes** —
that boundary is a structural fact, not a documented promise, and
`TestSentinelCannotExecute` below checks it by enumerating this module's
public callables.

WHAT WAS AUDITED BEFORE BUILDING

No monitoring, queue producer, health-report generator, or scheduled
sweep exists anywhere in this repository — `PARETO_FRONTIER.md`/
`NEXT_MOVE.md`/`BUILD_REPORT.md` are all hand-maintained prose, updated
manually each cycle, never generated by a deterministic check. No
scheduler exists (no GitHub remote — same standing fact as
`PARETO_FRONTIER.md` FRONTIER-003), so this module implements only
Level 1 (Pulse Sweep) — deterministic, cheap, no model-based review —
and leaves Level 2 (Deep Sweep, semantic) and Level 3 (Strategic
Compaction Review) as doctrine, not code, per the source directive's own
"use model-based review only for semantic questions deterministic code
cannot answer" instruction. Building Level 2/3 as code now, with no
Level 1 in production use yet to prove the pattern, would be exactly the
"busiest system" the source directive's own Final Doctrine warns
against.

WHY THE CHECKS CHOSEN ARE THE ONES CHOSEN

Each of the four `check_*` functions below was picked because running it
against the real repository (not a synthetic fixture) found something
true: `check_claude_md_imports` confirms every `@`-import target exists
(currently: yes); `check_subsystem_build_reports` finds three real
subsystems (`schema/`, `firewall/`, `narrative/`) with no `BUILD_REPORT.md`
at all, unlike their five siblings; `check_python_syntax` is a zero-cost
correctness net; `check_duplicate_frontier_ids` guards the one append-only
registry (`PARETO_FRONTIER.md`) this repo already relies on humans to
keep internally consistent by hand.

CT_141 COMPACTION

`pulse_sweep()` applies the source directive's CT_141 rule directly: if
raw finding count exceeds `COMPACTION_THRESHOLD`, the report is
compacted into a summary (`compacted=True`, `findings` truncated to the
highest-confidence subset) rather than dumping every finding — "never
respond to overwhelm by generating more unverified work."
"""

from __future__ import annotations

import ast
import json
import re
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

__all__ = [
    "Finding",
    "HealthReport",
    "PathProposal",
    "FourPaths",
    "pulse_sweep",
    "consolidate",
    "format_four_paths",
    "PulseContinuity",
    "read_pulse_continuity",
    "PULSE_LOG_MAX_RECORDS",
    "SUBSYSTEMS_REQUIRING_BUILD_REPORT",
    "COMPACTION_THRESHOLD",
    "HOLD_CLASSES",
    "classify_hold",
    "check_mouth_health",
    "LIVE_MOUTH_IDS",
    "count_real_tests",
    "check_readme_test_count",
    "check_sigil_snapshot_agreement",
    "check_frontier_hash_placeholders",
    "check_protocol_document_targets",
    "PROTOCOL_COMMAND_DIR",
    "CRON_STDERR_TAIL_BYTES",
    "CronStderrReport",
    "read_cron_stderr",
    "HUNT_SURFACE_STATUSES", "HuntSurface", "ContinuationDecision",
    "evaluate_continuation", "select_one_admitted", "UnaccountedCandidates",
    "DEFERRED_LOG_SIZE_THRESHOLD_BYTES", "check_deferred_log_size_wake_condition",
]

CONFIDENCE_VALUES = frozenset({"HIGH", "MEDIUM", "LOW"})

# Subsystems this repo's own doctrine (CLAUDE.md "Standing facts") names
# as requiring a BUILD_REPORT.md. Fixed list, not auto-discovered — a
# directory becomes a "subsystem" by human decision, not by having a
# tests/ folder, so this check does not try to infer that decision.
SUBSYSTEMS_REQUIRING_BUILD_REPORT: tuple[str, ...] = (
    "schema", "firewall", "kpm", "magl", "rpa", "taal", "foundation", "narrative",
)

# CT_141: above this many raw findings in one sweep, compact rather than
# dump — deliberately small, this is a Level 1 sweep, not an incident report.
COMPACTION_THRESHOLD = 20

_EXCLUDED_DIRS = {".git", "__pycache__", "node_modules"}


@dataclass(frozen=True)
class Finding:
    """One Level-1 observation. `finding does not equal authorization` —
    nothing about a Finding's shape implies permission to act on it."""

    observation: str
    evidence_location: str
    confidence: str
    interpretation: str
    reversibility: str
    recommended_next_action: str

    def __post_init__(self) -> None:
        if self.confidence not in CONFIDENCE_VALUES:
            raise ValueError(
                f"confidence {self.confidence!r} must be one of {sorted(CONFIDENCE_VALUES)}"
            )
        if not self.evidence_location:
            raise ValueError(
                "a Finding requires evidence_location — a finding with no "
                "location is an opinion, not an observation."
            )

    def key(self) -> tuple[str, str]:
        """Identity used for deduplication: same observation at same location."""
        return (self.observation, self.evidence_location)


@dataclass(frozen=True)
class HealthReport:
    findings: tuple[Finding, ...]
    raw_finding_count: int
    compacted: bool


def consolidate(findings: list[Finding]) -> tuple[Finding, ...]:
    """Deduplicate findings sharing (observation, evidence_location).

    First occurrence wins — later duplicates carry no new location, so
    there is nothing to merge beyond dropping the repeat.
    """
    seen: dict[tuple[str, str], Finding] = {}
    for f in findings:
        seen.setdefault(f.key(), f)
    return tuple(seen.values())


def check_claude_md_imports(repo_root: Path) -> list[Finding]:
    claude_md = repo_root / "CLAUDE.md"
    if not claude_md.exists():
        return [Finding(
            observation="CLAUDE.md is missing",
            evidence_location=str(claude_md),
            confidence="HIGH",
            interpretation="boot configuration is entirely absent",
            reversibility="reversible — file can be restored from git history",
            recommended_next_action="HUMAN_REVIEW_REQUIRED",
        )]
    findings: list[Finding] = []
    for line in claude_md.read_text().splitlines():
        line = line.strip()
        if not line.startswith("@"):
            continue
        target = repo_root / line[1:]
        if not target.exists():
            findings.append(Finding(
                observation=f"CLAUDE.md @-imports a missing file: {line}",
                evidence_location=str(claude_md),
                confidence="HIGH",
                interpretation="doctrine index references a file that does not exist",
                reversibility="reversible — fix the reference or restore the file",
                recommended_next_action="DEFERRED_WITH_NEXT_ACTION: verify and repair the import",
            ))
    return findings


def check_subsystem_build_reports(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for name in SUBSYSTEMS_REQUIRING_BUILD_REPORT:
        subsystem_dir = repo_root / name
        if not subsystem_dir.is_dir():
            continue
        if not (subsystem_dir / "BUILD_REPORT.md").exists():
            findings.append(Finding(
                observation=f"subsystem '{name}' has no BUILD_REPORT.md",
                evidence_location=str(subsystem_dir),
                confidence="MEDIUM",
                interpretation=(
                    "every sibling subsystem carries a BUILD_REPORT.md with "
                    "limitations/human-decisions/next-work-cell sections; "
                    "this one does not, which may mean the audit trail for "
                    "this subsystem lives only in commit messages"
                ),
                reversibility="fully reversible — adding a document has no side effects",
                recommended_next_action="candidate for PARETO_FRONTIER.md, not auto-created",
            ))
    return findings


def check_python_syntax(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in repo_root.rglob("*.py"):
        if any(part in _EXCLUDED_DIRS for part in path.parts):
            continue
        try:
            ast.parse(path.read_text(), filename=str(path))
        except SyntaxError as exc:
            findings.append(Finding(
                observation=f"syntax error: {exc.msg}",
                evidence_location=f"{path}:{exc.lineno}",
                confidence="HIGH",
                interpretation="file cannot be parsed by Python",
                reversibility="reversible — a syntax error blocks nothing until imported",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
    return findings


def check_duplicate_frontier_ids(repo_root: Path) -> list[Finding]:
    frontier_md = repo_root / "PARETO_FRONTIER.md"
    if not frontier_md.exists():
        return []
    ids = re.findall(r"^### (FRONTIER-\S+)", frontier_md.read_text(), flags=re.MULTILINE)
    seen: set[str] = set()
    findings: list[Finding] = []
    for frontier_id in ids:
        if frontier_id in seen:
            findings.append(Finding(
                observation=f"duplicate frontier id: {frontier_id}",
                evidence_location=str(frontier_md),
                confidence="HIGH",
                interpretation="the same candidate id was used twice, risking confused status tracking",
                reversibility="reversible — rename one entry",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
        seen.add(frontier_id)
    return findings


# `## Active` and `## Blocked` entries are checked for the one field
# pair genuinely present in 100% of real entries at time of writing
# (verified by reading the file, not assumed) — `- **CURRENT:**` and
# `- **GAP:**`, always as the entry's first two bullets. `## Archive`
# (a one-line table, different shape entirely) and `## Rejected` are
# not checked — this validator verifies declared structure is
# complete, per section, for the shape that section actually uses; it
# does not impose one schema on every section. It never judges whether
# an entry's content is strategically correct — only that the two
# always-present structural fields exist (`MARKDOWN_EXECUTION_
# BOUNDARY_001`'s own Anti-Overreach Law: structural validity != strategic truth).
_FRONTIER_ENTRY_SECTIONS = ("## Active", "## Blocked")



# THE BLIND SPOT THIS CLOSES (reproduced 2026-08-28 before building):
# `cron_pulse.py` writes an `UNAVAILABLE` record whenever a mouth's fetch
# fails, and that per-mouth try/except is deliberate -- one mouth's
# failure must never sink the tick. But nothing ever converted those
# records into a Finding, so the hourly sweep reported
# `raw_finding_count=0` -- indistinguishable from perfect health -- while
# a mouth had failed five consecutive times. Directly reproduced: five
# UNAVAILABLE records in a row produced zero mouth-related findings.
#
# That is the worst shape a monitoring failure can take: silent loss of
# the organism's only sensory organs, reported as health. Every other
# check in this module inspects the repository as a set of documents;
# this is the first that inspects whether the live sensing apparatus is
# still working. That is a genuinely new information channel, not a
# second name for something already reported.
#
# WHY TWO CONSECUTIVE FAILURES, NOT ONE: a single failed fetch is normal
# variation for network I/O -- PyPI and GitHub will occasionally 503,
# rate-limit, or lose a DNS lookup, and a blip that recovers on the next
# tick is the system working as designed (prior state is preserved
# untouched). Requiring the two most recent observations to BOTH be
# UNAVAILABLE is what separates a real persistent failure from weather.
# This is the "distinguish transient from repeated" distinction that was
# correctly killed twice in earlier cycles for having no consumer; it is
# earned now only because `Finding` -> `pulse_log.jsonl` ->
# `read_pulse_continuity()` -> `/boot` was subsequently proven complete
# end to end.
#
# The observation text is deliberately STABLE -- no counts, no
# timestamps -- so `Finding.key()` collapses a persistent failure to one
# finding for as long as it lasts, and it disappears by itself on the
# first successful fetch. A streak counter in the text would change the
# key every tick and spam the boot report, which is the exact failure
# this repository's dedupe discipline exists to prevent.
#
# Fixed list, not a glob, for the same reason
# SUBSYSTEMS_REQUIRING_BUILD_REPORT is fixed: `foundation/` still
# contains `mouth_pypi_log.jsonl`, an orphan from an earlier MOUTH_ID
# naming that nothing writes any more. A glob would report it stale
# forever with no remedy but deletion -- a static fact re-reported
# eternally, which is a kill criterion, not a finding.
LIVE_MOUTH_IDS: tuple[str, ...] = ("pypi_pyyaml_releases", "github_pyyaml_releases")


def check_mouth_health(repo_root: Path, now: Optional["datetime"] = None) -> list[Finding]:
    """Convert persistent mouth failure or a stopped mouth clock into
    Findings. Read-only, bounded (at most LOG_MAX_RECORDS lines per
    mouth, two mouths), fail-soft on malformed lines.

    A missing log is NOT a finding: on a fresh clone the mouths have
    simply never run, which is the correct initial state."""
    from foundation.mouth_common import LOG_MAX_RECORDS, LOG_STALE_AFTER_SECONDS

    findings: list[Finding] = []
    for mouth_id in LIVE_MOUTH_IDS:
        log_path = repo_root / "foundation" / f"mouth_{mouth_id}_log.jsonl"
        if not log_path.exists():
            continue
        try:
            lines = [l for l in log_path.read_text(encoding="utf-8").splitlines() if l.strip()]
        except OSError:
            continue

        records = []
        for line in lines[-LOG_MAX_RECORDS:]:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            # A line can be valid JSON and still not be a record (a bare
            # number or string from a truncated/partial write). Found by
            # adversarial review 2026-08-28: `.get()` on such a value raised
            # AttributeError out of this check and out of pulse_sweep(),
            # taking down EVERY other check's findings with it -- one
            # malformed byte disabling the whole hourly sweep.
            if not isinstance(obj, dict):
                continue
            records.append(obj)
        if not records:
            continue

        recent = records[-2:]
        if len(recent) == 2 and all(r.get("status") == "UNAVAILABLE" for r in recent):
            findings.append(Finding(
                observation=(
                    f"mouth {mouth_id!r} failed its two most recent observations "
                    f"-- persistent fetch failure, not a transient blip"
                ),
                evidence_location=str(log_path),
                confidence="HIGH",
                interpretation=(
                    "this repository's only sensory organs are its two mouths. "
                    "A persistently failing mouth means external change is no "
                    "longer being observed at all, while the pulse otherwise "
                    "reports normally -- silent sensory loss. Prior state is "
                    "preserved untouched by design, so nothing is corrupted; "
                    "the cost is blindness, not damage. Most recent error: "
                    + str(records[-1].get("error", "not recorded"))[:200]
                ),
                reversibility=(
                    "fully reversible -- observation only; the finding clears "
                    "itself on the first successful fetch"
                ),
                recommended_next_action=(
                    "HUMAN_REVIEW_REQUIRED: check network reachability and "
                    "whether the feed URL still resolves"
                ),
            ))
            continue

        latest_ts = records[-1].get("observed_at") or records[-1].get("timestamp")
        parsed = _parse_iso(latest_ts) if latest_ts else None
        if parsed is None:
            continue
        from datetime import datetime as _dt, timezone as _tz
        current = now if now is not None else _dt.now(_tz.utc)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=_tz.utc)
        if current.tzinfo is None:
            current = current.replace(tzinfo=_tz.utc)
        if (current - parsed).total_seconds() > LOG_STALE_AFTER_SECONDS:
            findings.append(Finding(
                observation=(
                    f"mouth {mouth_id!r} has stopped writing observations "
                    f"(newest record older than the staleness threshold)"
                ),
                evidence_location=str(log_path),
                confidence="MEDIUM",
                interpretation=(
                    "the mouth is not failing -- it is not running at all. "
                    "Distinct from a fetch failure: no UNAVAILABLE records are "
                    "being written either, which points at the clock (the cron "
                    "entry) rather than the network. See "
                    "foundation/cron_pulse.err.log via read_cron_stderr()."
                ),
                reversibility="fully reversible -- observation only",
                recommended_next_action=(
                    "HUMAN_REVIEW_REQUIRED: confirm the cron entry is still "
                    "installed and check cron_pulse.err.log"
                ),
            ))
    return findings

# README's headline test count is the single most-repeated stale claim in
# this repository's history. It has been corrected by hand at least twice
# for README specifically (`cdce3df`: claimed 1,461, actual 1,508 -- whose
# own commit message calls it "second real drift instance found"), and the
# same mechanism has bitten CAPABILITY_MANIFEST.json (`f75a418`), CLAUDE.md's
# sigil paragraph (TIER:T7 long after the real value fell to T3), and two
# BUILD_REPORTs (`8c6e18f`, `289c2e1`). Every one of those was caught by a
# human re-running the real count by hand.
#
# That is the exact profile this sweep exists for: a mechanical, verifiable
# claim about the repository that drifts silently and has repeatedly cost
# human attention. It is deliberately a `Finding`, not an error -- README
# being briefly behind during active development is normal and expected;
# what was missing was any mechanism that noticed at all.
_README_TEST_COUNT_PATTERN = re.compile(r"\*\*([\d,]+)\s+tests\s+across", re.I)
_TEST_DEF_PATTERN = re.compile(r"^\s*def\s+test_\w+\s*\(", re.M)


def count_real_tests(repo_root: Path) -> int:
    """Count `def test_*` across every tests/ directory. Deliberately a
    static count, not a test run: this must stay cheap enough for the
    hourly pulse (no subprocess), unlike sigil.py's PROOF dimension which
    genuinely executes the suites and costs ~40s."""
    total = 0
    for path in repo_root.rglob("test_*.py"):
        if any(part in _EXCLUDED_DIRS for part in path.parts):
            continue
        try:
            total += len(_TEST_DEF_PATTERN.findall(path.read_text(encoding="utf-8")))
        except OSError:
            continue
    return total


def check_readme_test_count(repo_root: Path) -> list[Finding]:
    readme = repo_root / "README.md"
    if not readme.exists():
        return []
    try:
        text = readme.read_text(encoding="utf-8")
    except OSError:
        return []
    match = _README_TEST_COUNT_PATTERN.search(text)
    if match is None:
        return []
    claimed = int(match.group(1).replace(",", ""))
    actual = count_real_tests(repo_root)
    if claimed == actual:
        return []
    return [Finding(
        # STABLE observation -- no counts, no delta. Found by adversarial
        # review 2026-08-28: the original text interpolated `actual` and the
        # delta, so Finding.key() changed on every tick where the real count
        # moved while README stayed stale -- i.e. on exactly the normal
        # development lag this check's own interpretation calls expected.
        # Reproduced: three ticks of a single persisting condition produced
        # three distinct keys, which spams /boot instead of deduping. The
        # numbers belong in `interpretation`, which is not part of the key.
        observation="README.md's declared test count disagrees with a real count of `def test_`",
        evidence_location=str(readme),
        confidence="HIGH",
        interpretation=(
            f"README.md claims {claimed:,}; a real count of `def test_` across "
            f"every tests/ directory finds {actual:,} ({actual - claimed:+,}). "
            "a hand-maintained numeric claim has drifted from recomputed "
            "ground truth -- the single most-repeated stale-claim class in "
            "this repository's history (see this function's own comment for "
            "the commits). Not necessarily wrong to leave: README is "
            "expected to lag during active development, and the static "
            "`def test_` count is not identical to the number unittest "
            "reports (parameterised or skipped tests differ). It is the "
            "silence that was the defect, not the lag."
        ),
        reversibility="fully reversible -- observation only, nothing is rewritten",
        recommended_next_action=(
            "HUMAN_REVIEW_REQUIRED: re-run the real suites and update "
            "README.md's count, or confirm the lag is intentional"
        ),
    )]


# SECOND MEMBER OF THE SAME DRIFT FAMILY, and deliberately NOT a generic
# "declared vs observed" framework -- the shared abstraction is `Finding`,
# which already exists; two small checks that both emit one need no third
# layer between them.
#
# THE REAL, PROVEN OCCURRENCE: CLAUDE.md's inline Capability Sigil
# paragraph carried `TIER:T7 | ... | REALITY:10` after SIGIL.md had
# already recorded the real, evidenced drop to `TIER:T3 | ... |
# REALITY:6` (the network mouth was added, so the zero-network bonus was
# no longer earned). Two hand-maintained snapshots of ONE computed value
# disagreed, and a session booting off the stale one would orient from a
# capability index four tiers too high. Caught by a human reading prose,
# 2026-08-28 -- the same way every other member of this family was caught.
#
# WHAT THIS CHECK HONESTLY IS: a cheap disagreement detector, not an
# authority. Comparing two documents tells you they disagree; it does NOT
# tell you which is right, because neither is ground truth --
# `compute_sigil()` is, and it costs ~40s because it genuinely runs every
# subsystem's test suite. That asymmetry is the whole point: this is a
# sub-second Level-0 detector for when the expensive Level-1 recomputation
# is actually warranted. It reuses `sigil.parse_sigil()` exactly as built
# (already proven to find the line embedded in surrounding prose, and to
# fail closed on a partial line rather than invent zeros) and adds no new
# parsing of its own.
_SIGIL_SNAPSHOT_FILES = ("CLAUDE.md", "SIGIL.md")


def check_sigil_snapshot_agreement(repo_root: Path) -> list[Finding]:
    """Compare every recorded sigil snapshot in the repository against
    every other. Read-only, no subprocess, no test execution.

    A file with no sigil line contributes nothing (absence is a valid
    state -- not every document must carry a snapshot). Fewer than two
    snapshots means there is nothing to disagree, so no finding."""
    from foundation.sigil import DIMENSION_NAMES, parse_sigil

    snapshots = []
    for name in _SIGIL_SNAPSHOT_FILES:
        path = repo_root / name
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        recorded = parse_sigil(text, source=str(path))
        if recorded is not None:
            snapshots.append((name, recorded))

    if len(snapshots) < 2:
        return []

    base_name, base = snapshots[0]
    findings: list[Finding] = []
    for other_name, other in snapshots[1:]:
        differing = [
            n for n in DIMENSION_NAMES if getattr(base, n) != getattr(other, n)
        ]
        if base.tier != other.tier:
            differing.append("tier")
        if not differing:
            continue
        findings.append(Finding(
            observation=(
                f"recorded sigil snapshots disagree between {base_name} and "
                f"{other_name} on: {', '.join(sorted(differing))}"
            ),
            evidence_location=str(repo_root / other_name),
            confidence="HIGH",
            interpretation=(
                "two hand-maintained snapshots of one computed value have "
                "diverged, so at least one is stale. This check cannot say "
                "which -- neither document is ground truth. Only "
                "foundation/sigil.py::compute_sigil() is, and it costs ~40s "
                "because it really runs every subsystem's suite. This is the "
                "cheap detector for when that expensive recomputation is "
                "warranted. Proven to have happened: CLAUDE.md read TIER:T7 "
                "long after SIGIL.md recorded the real drop to TIER:T3."
            ),
            reversibility="fully reversible -- observation only, nothing is rewritten",
            recommended_next_action=(
                "HUMAN_REVIEW_REQUIRED: run compute_sigil()/reconcile_sigil() "
                "and update whichever snapshot is stale -- never reconcile the "
                "two documents to each other without recomputing"
            ),
        ))
    return findings


# THE BLIND SPOT THIS CLOSES (reproduced 2026-08-28 before building): a
# session adding a PARETO_FRONTIER.md Archive row mid-cycle writes the
# literal string "(this commit)" as a hash placeholder, intending to
# backfill the real hash after committing -- and repeatedly forgets.
# `5a9ca9f` fixed one row and named the pattern recurring; that very fix's
# own message records that "all four prior cycles above were uncommitted
# in the working tree (their (this commit) tags were false)". Confirmed
# live and current, not historical: `git diff --stat PARETO_FRONTIER.md`
# shows the working tree matches HEAD exactly, so the 7 placeholder rows
# on disk right now are genuinely committed, stale content -- not an
# in-progress edit `pulse_sweep()` is catching mid-keystroke.
#
# Mechanical ground truth needs no git history: the literal substring
# "(this commit)" can only be true transiently, during the act of
# authoring, and is unconditionally wrong in anything already on disk
# for a scheduled sweep to read.
#
# Observation text is deliberately STABLE (no count) -- the same
# discipline check_readme_test_count() was found to violate this same
# shift (a count in the key spams /boot on every tick the count moves
# while the condition persists). The row count belongs in
# `interpretation`.
# Matches only an actual table-cell placeholder (bounded by pipes), not a
# prose MENTION of the phrase. Found and fixed before shipping: line 145
# of the real PARETO_FRONTIER.md discusses this exact historical bug in
# its own text ("their `(this commit)` tags were false"), which a bare
# substring count would double-count as a second live placeholder on a
# row that only has one. Same false-positive class already found once
# this shift in sigil.py::parse_sigil() (CLAUDE.md's own correction
# narrative mentions "TIER:T7" in prose) -- structural matching, not
# substring containment, is the fix both times.
_ARCHIVE_HASH_PLACEHOLDER_CELL = re.compile(r"\|\s*\(this commit\)\s*\|")


def check_frontier_hash_placeholders(repo_root: Path) -> list[Finding]:
    """Detect PARETO_FRONTIER.md Archive rows still carrying the literal
    hash placeholder. Read-only, no subprocess, no git call."""
    path = repo_root / "PARETO_FRONTIER.md"
    if not path.exists():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    count = len(_ARCHIVE_HASH_PLACEHOLDER_CELL.findall(text))
    if count == 0:
        return []
    return [Finding(
        observation="PARETO_FRONTIER.md has unresolved Archive hash placeholder(s)",
        evidence_location=str(path),
        confidence="HIGH",
        interpretation=(
            f"{count} unresolved Archive table cell(s) still reading "
            f"'(this commit)'. This string is only ever "
            f"legitimately true during active mid-edit authoring, before a "
            f"commit exists to name -- anything already on disk for a "
            f"scheduled sweep to read is either a real backfill gap or a "
            f"currently-open edit. See commit `5a9ca9f` for the one prior "
            f"fix and its own note that this class has recurred at least "
            f"four times before that."
        ),
        reversibility="fully reversible -- observation only, nothing is rewritten",
        recommended_next_action=(
            "HUMAN_REVIEW_REQUIRED: backfill the real commit hash for each "
            "placeholder row, or confirm the row is mid-edit and not yet "
            "committed"
        ),
    )]


def check_frontier_schema(repo_root: Path) -> list[Finding]:
    frontier_md = repo_root / "PARETO_FRONTIER.md"
    if not frontier_md.exists():
        return []
    text = frontier_md.read_text()
    lines = text.splitlines()

    findings: list[Finding] = []
    current_section: str | None = None
    current_entry_id: str | None = None
    entry_lines: list[str] = []

    def _check_entry(entry_id: str, body_lines: list[str]) -> None:
        body = "\n".join(body_lines)
        for field_name in ("- **CURRENT:**", "- **GAP:**"):
            if field_name not in body:
                findings.append(Finding(
                    observation=f"{entry_id} is missing required field {field_name}",
                    evidence_location=f"{frontier_md}::{entry_id}",
                    confidence="HIGH",
                    interpretation=(
                        "every Active/Blocked entry has carried CURRENT and GAP "
                        "as its first two bullets in this file's real history; "
                        "this entry does not"
                    ),
                    reversibility="reversible — add the missing bullet",
                    recommended_next_action="review if publishing",
                ))

    for line in lines:
        if line.startswith("## "):
            if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
                _check_entry(current_entry_id, entry_lines)
            current_section = line.strip()
            current_entry_id = None
            entry_lines = []
            continue
        if line.startswith("### FRONTIER"):
            if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
                _check_entry(current_entry_id, entry_lines)
            match = re.match(r"### (FRONTIER-\S+)", line)
            current_entry_id = match.group(1) if match else line.strip()
            entry_lines = []
            continue
        entry_lines.append(line)

    if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
        _check_entry(current_entry_id, entry_lines)

    return findings


PULSE_LOG_MAX_RECORDS = 20

# cron_pulse.py is scheduled hourly (see the crontab entry it was
# installed with). 3x the expected interval is stale enough to mean
# "the clock likely stopped," not "it just hasn't ticked yet this hour."
PULSE_EXPECTED_INTERVAL_SECONDS = 3600
PULSE_STALE_AFTER_SECONDS = 3 * PULSE_EXPECTED_INTERVAL_SECONDS


@dataclass(frozen=True)
class PulseContinuity:
    """Bounded, read-only view of what `foundation/cron_pulse.py` observed
    while nobody was in a session. Boot-time answer to "what happened
    while the clock was running alone" — never more than that. A
    non-empty `meaningful_findings` is evidence to look at, not something
    already authorized to act on (same `finding != authorization` rule
    as every other Finding in this module).

    `stale=True` means the latest record is older than
    `PULSE_STALE_AFTER_SECONDS` — the clock may have stopped running.
    `stale=False` on an empty/unavailable log is not a health claim
    (there is nothing to be stale); check `available` first.
    """

    available: bool
    latest_timestamp: Optional[str]
    records_considered: int
    meaningful_findings: tuple[Finding, ...]
    warnings: tuple[str, ...]
    source: str
    stale: bool = False

    # Added 2026-08-28 after reproducing a real semantic hole: every
    # pulse record on disk carries `raw_finding_count` and `compacted`
    # (pulse_sweep() writes both, and CT_141 compaction sets
    # compacted=True while truncating `findings` to the highest-confidence
    # COMPACTION_THRESHOLD), but this view carried neither -- so a
    # CT_141-throttled sweep of 45 findings and an honest sweep of 2 were
    # indistinguishable to `/boot` step 4b, the only real consumer. The
    # throttle firing is exactly the kind of event a boot report must not
    # silently swallow: it is this repository's panic axiom actually
    # engaging. `truncated_findings` is the count of findings that
    # existed but are not in `meaningful_findings`.
    raw_finding_count: int = 0
    compacted: bool = False

    @property
    def truncated_findings(self) -> int:
        return max(0, self.raw_finding_count - len(self.meaningful_findings))


def _parse_iso(ts: str) -> Optional["datetime"]:
    from datetime import datetime
    try:
        return datetime.fromisoformat(ts)
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------------
# THE CONTINUATION GOVERNOR
#
# THE GAP THIS CLOSES: nothing in this repository formalised the
# difference between "this board found nothing" and "the accessible
# search space is exhausted." Every prior autonomous-cycle pass in this
# session collapsed the two informally, in prose, which meant the
# decision to stop was never checkable -- a future reader could not tell
# whether a stop was earned or merely convenient. This makes the eight
# stop preconditions a pure, testable function instead of a paragraph.
#
# THIS IS A DECISION FUNCTION, NOT AN ACTUATOR. It classifies whether
# governed hunting may legitimately halt. It executes nothing, schedules
# nothing, and calls nothing. SIGIL.NO_EXECUTION_AUTHORITY is unaffected
# by construction -- there is no code path here that performs an action,
# only one that returns a label, exactly like `classify_hold()` above.
# `TestSentinelCannotExecute` (this file's own structural guard) already
# covers it: neither `HuntSurface`, `evaluate_continuation`, nor
# `select_one_admitted` starts with a forbidden execution verb.
# ---------------------------------------------------------------------------

HUNT_SURFACE_STATUSES = frozenset({
    "UNSWEPT", "PARTIAL", "SWEPT", "BLOCKED", "DUPLICATE",
    "DEFERRED_WITH_OBJECTIVE_WAKE_CONDITION",
})

_STATUSES_REQUIRING_EVIDENCE = frozenset({"BLOCKED", "DUPLICATE"})


@dataclass(frozen=True)
class HuntSurface:
    """One row of the governor's coverage ledger. Fail-closed at
    construction, not merely by convention: a BLOCKED or DUPLICATE surface
    with no stated evidence, or a DEFERRED surface with no stated reopen
    condition, cannot be built -- 'seems subjective' or 'future work'
    cannot enter the ledger as if it were a real evidenced block."""

    name: str
    status: str
    evidence: str = ""
    reopen_condition: str = ""
    duplicate_of: str = ""

    def __post_init__(self) -> None:
        # AN IDENTITY MUST BE NAMEABLE. Reproduced 2026-08-28: `name` was
        # the only field never validated, while `duplicate_of` -- which
        # merely POINTS AT a name -- has always required non-blank after
        # .strip(). That asymmetry let a blank identity onto the board:
        #   * CONTINUE reported unresolved=('',) / ('   ',) / ('\t',),
        #     naming "work" no worker can act on -- the paralysis failure
        #     mode dressed as a populated tuple
        #   * a blank-named SWEPT row plus a blank candidate certified
        #     HARD_STOP -- FALSE CLOSURE over an unnameable identity
        #   * '' and '   ' coexisted as DISTINCT identities, so identity
        #     singularity cannot protect what has no legible identity
        #
        # .strip() is used only to decide blankness, never to normalise:
        # ' A' and 'A' remain distinct identities, because canonicalising
        # them was separately killed with evidence as speculative.
        if not isinstance(self.name, str):
            raise ValueError(
                f"HuntSurface name must be a str, not "
                f"{type(self.name).__name__} -- a non-string identity "
                f"previously escaped as a raw AttributeError from .strip(), "
                f"outside the verdict algebra entirely."
            )
        # Blank means "renders as nothing", not merely "is whitespace".
        # Mutation run 2026-08-28 found U+200B, U+FEFF and U+2060 all
        # constructing successfully: isspace() is False for them, so
        # .strip() leaves them intact, yet an identity made only of
        # zero-width characters is invisible and therefore exactly as
        # unnameable as "". They are Unicode category Cf (format);
        # every legitimate name character tested (Lu, Nd, So, Lo, Pd)
        # is not, so Cf is a clean separator, not a heuristic.
        # 'a\u200bb' stays lawful -- only wholly-invisible names are refused.
        legible = "".join(
            c for c in self.name
            if not c.isspace() and unicodedata.category(c) != "Cf"
        )
        if not legible:
            raise ValueError(
                f"HuntSurface name {self.name!r} is blank or wholly "
                f"invisible -- an identity that cannot be named cannot be "
                f"adjudicated, reported as reachable work, or targeted by a "
                f"duplicate. `duplicate_of` has always required a non-blank "
                f"target; the identity it points at must meet the same "
                f"standard."
            )
        if self.status not in HUNT_SURFACE_STATUSES:
            raise ValueError(
                f"HuntSurface status {self.status!r} must be one of "
                f"{sorted(HUNT_SURFACE_STATUSES)}"
            )
        if self.status in _STATUSES_REQUIRING_EVIDENCE and not self.evidence.strip():
            raise ValueError(
                f"HuntSurface {self.name!r} is {self.status} but has no "
                f"evidence -- a block without a stated reason is not a "
                f"block, it is an unswept surface wearing a disguise"
            )
        # DUPLICATE was a trash chute: adversarial pass 2026-08-28 proved
        # a surface could be disposed as DUPLICATE with no canonical
        # target at all, and STOP was still certified. Reproduced four
        # ways -- no target, nonexistent target, self-reference, and a
        # circular B->C->B chain -- every one returned STOP while the
        # work was really unresolved. A structural field, not prose in
        # `evidence`, because the target is an identity that must be
        # resolvable against the surface list, not a sentence to read.
        if self.status == "DUPLICATE":
            if not self.duplicate_of.strip():
                raise ValueError(
                    f"HuntSurface {self.name!r} is DUPLICATE but names no "
                    f"`duplicate_of` canonical target -- DUPLICATE without a "
                    f"target is a disposal chute, not a disposition"
                )
            if self.duplicate_of.strip() == self.name:
                raise ValueError(
                    f"HuntSurface {self.name!r} is marked DUPLICATE of itself "
                    f"-- self-reference resolves nothing"
                )
        if self.status == "DEFERRED_WITH_OBJECTIVE_WAKE_CONDITION" and not self.reopen_condition.strip():
            raise ValueError(
                f"HuntSurface {self.name!r} is deferred but names no "
                f"objective reopen condition -- a deferral with no wake "
                f"condition can never legitimately be revisited"
            )


@dataclass(frozen=True)
class ContinuationDecision:
    """The governor's output. `proceed=True` means: at least one
    HARD_STOP precondition is unmet, so ending the session now would
    require inventing pressure rather than following evidence.
    `proceed=False` means all eight preconditions held simultaneously."""

    proceed: bool
    reason: str
    unresolved_surfaces: tuple[str, ...]
    conditions: dict  # the 8 named preconditions -> bool, for audit

    def to_dict(self) -> dict:
        return {
            "proceed": self.proceed, "reason": self.reason,
            "unresolved_surfaces": list(self.unresolved_surfaces),
            "conditions": dict(self.conditions),
        }


class UnaccountedCandidates(ValueError):
    """Raised when a cycle reports discovering candidates that have no
    governed representation. Fail-closed: the governor refuses to render
    ANY decision -- not merely a STOP -- against an accounting universe
    it can prove is incomplete."""


def evaluate_continuation(
    surfaces: tuple,
    *,
    state_revalidated: bool,
    new_wake_evidence: bool = False,
    candidates_found: Optional[tuple] = None,
) -> ContinuationDecision:
    """The eight HARD_STOP preconditions, evaluated together. STOP
    (`proceed=False`) only when every one holds; any single unmet
    precondition means CONTINUE, and `unresolved_surfaces` names exactly
    what the next governed hunt cycle should target.

    Pure function -- no I/O, no side effects, deterministic in its
    inputs. The caller (a session or a future automated invocation) is
    responsible for actually re-checking live state before setting
    `state_revalidated=True`; this function cannot verify that claim
    itself, the same way `classify_hold()` trusts its caller's facts."""
    # CLOSED ACCOUNTING UNIVERSE (added 2026-08-28 after the escape was
    # directly reproduced, not reasoned about). The predicate below
    # validates the CONTENTS of `surfaces`, but nothing previously
    # validated that `surfaces` ACCOUNTS FOR WHAT THE CYCLE FOUND. The
    # exact 9-step escape, reproduced: a worker finds candidates X and Y,
    # the one-brick limit selects Y, the worker calls X "deferred, a
    # one-line future addition" in receipt PROSE ONLY, never builds a
    # HuntSurface row for it, and evaluate_continuation() -- which cannot
    # see candidates at all -- happily returns STOP while X remains real,
    # known, ungoverned work.
    #
    # This is the author's own prior cycle: `harness_boot_documentation`
    # was reported as DEFERRED with the words "not lost" and "no board
    # created for it," and grep confirms it appeared in no source file,
    # no test, and no durable artifact. "Not lost" was not a state.
    #
    # Fail-closed by raising rather than returning proceed=True: a
    # governor that cannot prove its universe is closed must not render
    # a verdict at all. Returning CONTINUE would let a worker treat the
    # violation as ordinary work-remaining and quietly lose X anyway.
    # "ZERO CANDIDATES FOUND" and "CANDIDATE ACCOUNTING NOT PROVIDED" are
    # different states. Reproduced 2026-08-28: `candidates_found` defaulted
    # to `()`, so simply OMITTING the argument silently disabled the whole
    # conservation mechanism and STOP was certified with real unlisted work.
    # That is an escape reachable by doing nothing at all -- no malformed
    # input, no bad row, just a missing keyword. The default is now None
    # (= not provided), which refuses a verdict; an explicit `()` remains a
    # legitimate positive claim that the cycle genuinely found nothing.
    # THE SAME ROOT CLASS, ON THE SIBLING PARAMETER. The previous cycle
    # enforced a concrete-collection contract on `candidates_found` and
    # left `surfaces` -- declared `tuple`, never checked -- unenforced.
    # `surfaces` is iterated SEVEN times in one call (conservation,
    # identity map, duplicate index, chain walk, unresolved scan, the
    # evidence and reopen-condition all() checks, len()). Any input whose
    # observation mutates its future semantics therefore reads as a
    # DIFFERENT universe at each gate.
    #
    # Reproduced 2026-08-28 with an object exposing __len__ (so the
    # non-empty gate passes) and a one-shot __iter__:
    #   * real UNSWEPT work certified HARD_STOP with unresolved=()
    #   * a duplicate pointing at a nonexistent target certified HARD_STOP
    # Both are FALSE CLOSURE, not merely a crash. Plain generators and
    # iterators additionally leaked a raw TypeError from len(), which is
    # outside the three-verdict algebra entirely.
    if not isinstance(surfaces, (tuple, list, set, frozenset)):
        raise UnaccountedCandidates(
            f"surfaces must be a concrete collection (tuple, list, set, "
            f"frozenset), not {type(surfaces).__name__}. This function reads "
            f"surfaces repeatedly across every jurisdiction gate; an input "
            f"whose iteration is one-shot presents a different universe to "
            f"each gate and can certify closure over work it already "
            f"consumed."
        )

    # A ONE-SHOT ITERATOR IS NOT A CLAIM. Reproduced 2026-08-28: the
    # `tuple` type contract was declared and never enforced, so a
    # generator or iterator could be passed. Two escapes followed, both
    # certifying HARD_STOP with real ungoverned work:
    #
    #   1. RETRY-AFTER-REFUSAL. The SAME iterator object yields
    #      NO_VERDICT on call 1 (ghost detected) and HARD_STOP on call 2
    #      (iterator now exhausted, reads as an empty claim). Retrying
    #      after a jurisdiction denial is the natural worker response to
    #      being refused, and it silently converted refusal into closure.
    #
    #   2. EMPTY GENERATOR. Generators are ALWAYS truthy, including empty
    #      ones, so `if candidates_found:` passed while the object
    #      asserted nothing -- defeating the omitted-vs-explicitly-empty
    #      distinction the None default exists to protect.
    #
    # The corruption reached the error text itself: call 1's message read
    # "cycle reported finding []" because the iterator was already
    # drained by the time the message interpolated it. A guard whose own
    # evidence is destroyed by reading it cannot be trusted.
    #
    # Closure is the smallest available: require a concrete, re-readable
    # collection. No new type, no normalisation, no materialisation that
    # would silently accept an exhausted iterator as an empty claim.
    if candidates_found is not None and not isinstance(
        candidates_found, (tuple, list, set, frozenset)
    ):
        raise UnaccountedCandidates(
            f"candidates_found must be a concrete collection (tuple, list, "
            f"set, frozenset), not {type(candidates_found).__name__}. A "
            f"one-shot iterator is not a claim: it reads as its contents "
            f"once and as empty forever after, so the same object can be "
            f"refused and then certify closure on retry."
        )
    # PIN THE OBSERVATIONAL UNIVERSE. The type guards above reject
    # one-shot inputs, but type is not stability: a `list` SUBCLASS
    # passes isinstance() and can still override __iter__ to yield
    # different membership on each read. `surfaces` is read seven times
    # per call and `candidates_found` once, so without pinning, different
    # jurisdiction gates can adjudicate DIFFERENT UNIVERSES.
    #
    # Reproduced 2026-08-28 against current source, both FALSE CLOSURE:
    #   * a list subclass yielding its dirty row only on read 1 -- real
    #     UNSWEPT work certified HARD_STOP with unresolved=()
    #   * the same shape hiding a duplicate whose target does not exist
    #   * candidates_found truthy via __len__ but yielding nothing --
    #     a ghost candidate never checked, HARD_STOP issued
    #
    # Materialising once makes every gate read one immutable snapshot.
    # This does NOT claim to detect a caller that lies on its first read;
    # that is the same caller-assertion ceiling as `state_revalidated`,
    # and is declared as such rather than papered over. What it does
    # guarantee is that no single call can present one universe to the
    # conservation gate and a different one to the closure gates.
    surfaces = tuple(surfaces)

    # MEMBERS MUST BE LAWFUL ROWS, NOT MERELY PRESENT. Pinning fixed WHICH
    # objects the gates see; it never checked WHAT they are. Every
    # invariant this governor depends on lives in HuntSurface.__post_init__
    # -- status in the vocabulary, evidence present for BLOCKED/DUPLICATE,
    # reopen_condition present for DEFERRED, no self-referential duplicate
    # -- and all of them were bypassable by any duck-typed object.
    #
    # Reproduced 2026-08-28 against current source:
    #   * a row with status "TOTALLY_MADE_UP", outside the entire
    #     vocabulary, certified HARD_STOP -- unadjudicated work reported
    #     as closure
    #   * BLOCKED with no evidence, and DEFERRED with no reopen
    #     condition, each produced CONTINUE with unresolved=() -- the
    #     "continue naming no reachable work" paralysis already outlawed
    #   * a plain str element leaked a raw AttributeError, a fourth
    #     outcome outside the verdict algebra
    #
    # One isinstance check restores every bypassed construction invariant
    # at once, because HuntSurface cannot exist without having satisfied
    # them. Subclasses remain lawful: they still run __post_init__.
    non_rows = tuple(
        f"index {i}: {type(s).__name__}"
        for i, s in enumerate(surfaces) if not isinstance(s, HuntSurface)
    )
    if non_rows:
        raise UnaccountedCandidates(
            f"surfaces must contain only HuntSurface rows; found "
            f"{', '.join(non_rows)}. Every invariant this governor relies "
            f"on is enforced in HuntSurface's constructor, so a duck-typed "
            f"row bypasses status validation, evidence requirements, "
            f"reopen conditions, and self-reference refusal simultaneously."
        )

    if candidates_found is not None:
        candidates_found = tuple(candidates_found)

    if candidates_found is None:
        raise UnaccountedCandidates(
            "candidate accounting was not provided. Pass candidates_found "
            "explicitly -- `()` to positively assert this cycle discovered "
            "nothing, or the full tuple of discovered candidate identities. "
            "Omission is not a claim of emptiness, and the governor will not "
            "render a verdict against an unproven universe."
        )
    # CANDIDATE IDENTITIES MUST BE STRINGS. The conservation gate below
    # decides membership with `c not in named`, which delegates the
    # question "is this candidate accounted for" to the CANDIDATE'S OWN
    # __eq__/__hash__. An arbitrary object therefore adjudicates its own
    # conservation.
    #
    # Reproduced 2026-08-28, all against current source:
    #   * FALSE HARD_STOP -- an object with `__hash__ = hash("X")` and
    #     `__eq__` returning True is accepted as accounted for and
    #     certifies proceed=False, despite having no HuntSurface row at
    #     all. Closure over a candidate that was never disposed.
    #   * a list or dict element raises raw TypeError ("unhashable
    #     type") from the membership test -- a fourth outcome outside
    #     {NO_VERDICT, CONTINUE, HARD_STOP}.
    #   * mixed int/str elements raise raw TypeError from sorted() while
    #     BUILDING the refusal message, so the fail-closed path itself
    #     throws the wrong exception type.
    #
    # A surface identity is `HuntSurface.name`, a str. Requiring the
    # claim to speak the same type closes all three at once: membership
    # becomes str-to-str comparison the governor can reason about, and
    # both TypeError routes disappear because str is hashable and
    # totally ordered against str.
    if candidates_found is not None:
        non_str = tuple(
            f"index {i}: {type(c).__name__}"
            for i, c in enumerate(candidates_found) if not isinstance(c, str)
        )
        if non_str:
            raise UnaccountedCandidates(
                f"candidates_found must contain only identity strings; found "
                f"{', '.join(non_str)}. Membership is decided against "
                f"HuntSurface.name (a str); allowing arbitrary objects lets a "
                f"candidate's own __eq__ adjudicate whether it was accounted "
                f"for, and lets unhashable or unorderable elements escape as "
                f"raw TypeErrors outside the verdict algebra."
            )

    if candidates_found:
        named = {s.name for s in surfaces}
        unaccounted = tuple(c for c in candidates_found if c not in named)
        if unaccounted:
            raise UnaccountedCandidates(
                f"cycle reported finding {sorted(candidates_found)} but "
                f"{sorted(unaccounted)} has no HuntSurface row. Every "
                f"discovered candidate must carry exactly one governed "
                f"disposition (SWEPT/BLOCKED/DUPLICATE/DEFERRED/UNSWEPT/"
                f"PARTIAL). 'deferred', 'weaker', 'one-line future "
                f"addition', and 'not lost' are not states."
            )

    # SIGIL IV — IDENTITY LAW. One canonical identity may not carry
    # contradictory governing states. Reproduced 2026-08-28 in five
    # distinct constructions, all certifying HARD_STOP:
    #   SWEPT+BLOCKED, BLOCKED+SWEPT (reversed), SWEPT+DUPLICATE,
    #   SWEPT+DEFERRED, BLOCKED+DEFERRED, and a 3-row variant.
    # Order-independent: the first row did not win, the last row did not
    # win -- there was simply no identity check, so a clean row sat
    # beside a dirty row and the governor certified closure anyway.
    #
    # SWEPT+UNSWEPT happened to return CONTINUE, but only because P3
    # trips on the UNSWEPT row -- accidental safety from an unrelated
    # predicate, not adjudication. That is exactly the "incidental
    # CONTINUE != governed openness" conversion the contract forbids.
    #
    # Contradiction is neither work nor closure: it is loss of
    # jurisdiction, so this raises rather than returning CONTINUE.
    # Deliberately NOT banning repetition -- identical rows for one
    # identity are lawful and stay lawful (proven by test); only
    # DISTINCT dispositions for one identity are a contradiction.
    dispositions: dict = {}
    for surface in surfaces:
        dispositions.setdefault(surface.name, set()).add(surface.status)
    contradictory = {n: st for n, st in dispositions.items() if len(st) > 1}
    if contradictory:
        detail = "; ".join(
            f"{n!r} holds {sorted(st)}" for n, st in sorted(contradictory.items()))
        raise UnaccountedCandidates(
            f"identity contradiction -- one canonical identity may not carry "
            f"contradictory governing states: {detail}. Exactly one "
            f"disposition per identity is required; neither the first nor "
            f"the last row wins, and a clean row does not erase a dirty one."
        )

    # Every DUPLICATE must resolve, in finitely many hops, to a surface
    # that is NOT itself a duplicate. Construction already blocks an
    # empty or self-referential target; this closes the two remaining
    # reproduced escapes -- a target that does not exist in the universe
    # at all, and a circular chain (B->C, C->B) where no hop ever lands
    # on real governed state.
    by_name = {s.name: s for s in surfaces}
    for surface in surfaces:
        if surface.status != "DUPLICATE":
            continue
        seen_chain = {surface.name}
        cursor = surface.duplicate_of.strip()
        while True:
            target = by_name.get(cursor)
            if target is None:
                raise UnaccountedCandidates(
                    f"surface {surface.name!r} is DUPLICATE of {cursor!r}, "
                    f"which is not present in the governed universe -- the "
                    f"work it was folded into does not exist"
                )
            if cursor in seen_chain:
                raise UnaccountedCandidates(
                    f"DUPLICATE chain starting at {surface.name!r} is "
                    f"circular ({' -> '.join(sorted(seen_chain))}) -- no hop "
                    f"reaches real governed state"
                )
            seen_chain.add(cursor)
            if target.status != "DUPLICATE":
                break
            cursor = target.duplicate_of.strip()

    unresolved = tuple(
        s.name for s in surfaces if s.status in ("UNSWEPT", "PARTIAL")
    )
    conditions = {
        "1_state_revalidated": state_revalidated,
        "2_at_least_one_surface_recorded": len(surfaces) > 0,
        "3_no_unswept_or_partial_surface": len(unresolved) == 0,
        "4_every_block_or_duplicate_has_evidence": all(
            bool(s.evidence.strip())
            for s in surfaces if s.status in _STATUSES_REQUIRING_EVIDENCE
        ),
        "5_every_deferral_has_objective_wake_condition": all(
            bool(s.reopen_condition.strip())
            for s in surfaces if s.status == "DEFERRED_WITH_OBJECTIVE_WAKE_CONDITION"
        ),
        "6_no_new_wake_evidence": not new_wake_evidence,
        # Conditions 7/8 (no half-evaluated candidate; the stop itself is
        # receipted) are properties of HOW this function is called, not
        # of its inputs -- structurally guaranteed by HuntSurface's own
        # closed status vocabulary (no "half-evaluated" status exists to
        # construct) and by this function always returning a `reason`
        # string, never a bare boolean. Recorded here so all 8 remain
        # visible in one place, not silently 6.
        "7_no_half_evaluated_candidate": True,
        "8_decision_is_itself_receipted": True,
    }
    # SIGIL III / LAW XVII — JURISDICTION FAILURE IS NOT CONTINUATION.
    # Reproduced 2026-08-28: P1 (state not revalidated) and P2 (empty
    # universe) both returned proceed=True with unresolved_surfaces=(),
    # i.e. "reachable work remains" while naming no work at all. A worker
    # receiving that has no lawful next action -- it is CONTINUE by
    # accident of an unrelated predicate tripping, not governed openness.
    #
    # These two are categorically different from P3-P6: they are not
    # facts ABOUT the universe, they are the preconditions for having a
    # universe to judge. Revalidation absent = the state was never
    # checked. Zero surfaces = there is no governed universe. Neither is
    # evidence of open work; both are loss of jurisdiction, which the
    # constitution assigns to NO_VERDICT, never to a convenient verdict.
    #
    # Raised rather than returned, matching every other jurisdiction
    # denial in this function (unaccounted candidates, identity
    # contradiction, unresolvable duplicate chains): a governor that
    # cannot prove it may judge must render no verdict at all.
    jurisdiction_failures = [
        name for name in ("1_state_revalidated", "2_at_least_one_surface_recorded")
        if not conditions[name]
    ]
    if jurisdiction_failures:
        raise UnaccountedCandidates(
            f"jurisdiction denied -- {', '.join(jurisdiction_failures)}. "
            f"These are preconditions for having a governed universe at "
            f"all, not facts about one: an unrevalidated state was never "
            f"checked, and an empty surface set is not an open universe. "
            f"Neither is evidence of reachable work, so neither may be "
            f"reported as CONTINUE."
        )

    hard_stop = all(conditions.values())
    if hard_stop:
        return ContinuationDecision(
            proceed=False,
            reason=(
                "all 8 HARD_STOP preconditions held: state revalidated, "
                "every recorded surface is SWEPT/BLOCKED/DUPLICATE/"
                "DEFERRED with evidence, no unswept surface remains, no "
                "new wake evidence"
            ),
            unresolved_surfaces=(), conditions=conditions,
        )
    failed = [k for k, v in conditions.items() if not v]
    return ContinuationDecision(
        proceed=True,
        reason=f"HARD_STOP unproven -- failed precondition(s): {', '.join(failed)}",
        unresolved_surfaces=unresolved, conditions=conditions,
    )


def select_one_admitted(candidate_ids: tuple) -> object:
    """The one-brick-limit, enforced structurally rather than by
    discipline alone: given any number of admitted candidates, returns
    exactly one (the first, by caller-supplied priority order) or None.
    A caller that builds more than one candidate from a single governed
    cycle is not calling this function correctly -- it exists so that
    fact is checkable, not just documented."""
    return candidate_ids[0] if candidate_ids else None


# The one real DEFERRED_WITH_OBJECTIVE_WAKE_CONDITION item currently on
# the governor's board (see foundation/sentinel.py's own history) names
# a numeric threshold in free text: "any tracked JSONL log exceeds 1MB
# on disk." Condition 6 of evaluate_continuation() (no_new_wake_evidence)
# was being verified by a human reading `ls -la` each cycle -- the exact
# hand-checked-snapshot shape this session already proved costly twice
# (README test count, CLAUDE.md/SIGIL.md tier disagreement).
#
# Deliberately NOT a parser of `reopen_condition` prose -- that would be
# the English-string-as-machine-authority trap this session's own
# doctrine forbids for recommended_next_action. Instead, the one real
# threshold is a hardcoded constant, the same pattern
# mouth_common.MAX_FEED_BYTES already uses for its own real limit.
DEFERRED_LOG_SIZE_THRESHOLD_BYTES = 1_000_000

# The tracked JSONL logs this repository's conveyor actually writes.
# Fixed list, not a glob, for the same reason LIVE_MOUTH_IDS and
# SUBSYSTEMS_REQUIRING_BUILD_REPORT are fixed -- a stray or orphaned
# .jsonl file becoming "tracked" is a human decision, not automatic.
_TRACKED_JSONL_LOGS = (
    "pulse_log.jsonl",
    "mouth_pypi_pyyaml_releases_log.jsonl",
    "mouth_github_pyyaml_releases_log.jsonl",
    "authority_ledger.jsonl",
    "authority_runtime_tick_log.jsonl",
    "dependency_pressure_log.jsonl",
)


def check_deferred_log_size_wake_condition(repo_root: Path) -> bool:
    """Mechanically answer the one real deferred wake condition on the
    governor's board: has any tracked JSONL log exceeded
    `DEFERRED_LOG_SIZE_THRESHOLD_BYTES`? Read-only (`stat()` only, never
    opens or reads file content), bounded (a fixed file list, not a
    directory walk), fails soft (a missing file is not oversized).

    Returns True iff the "unbounded_log_read_before_slicing" surface
    should be reopened -- a future governor invocation can call this
    once instead of a human re-deriving it from `ls -la` by eye."""
    for name in _TRACKED_JSONL_LOGS:
        path = repo_root / "foundation" / name
        try:
            if path.stat().st_size > DEFERRED_LOG_SIZE_THRESHOLD_BYTES:
                return True
        except OSError:
            continue
    return False


def read_pulse_continuity(
    repo_root: Path,
    max_records: int = PULSE_LOG_MAX_RECORDS,
    now: Optional["datetime"] = None,
) -> PulseContinuity:
    """Read the tail of `foundation/pulse_log.jsonl` and summarise it.

    Read-only — never writes, truncates, or rotates the log. Bounded —
    reads at most `max_records` trailing lines regardless of file size,
    so a large log cannot flood a caller. Fails soft at every layer: a
    missing file, an empty file, and individual malformed JSON lines or
    malformed Finding payloads are all reported as `warnings`, never
    raised — a boot sequence must not fail because the heartbeat has
    never run or because one line got corrupted mid-write.
    """
    log_path = repo_root / "foundation" / "pulse_log.jsonl"
    source = str(log_path)

    if not log_path.exists():
        return PulseContinuity(
            available=False, latest_timestamp=None, records_considered=0,
            meaningful_findings=(),
            warnings=("pulse_log.jsonl does not exist yet — the cron pulse has never run",),
            source=source,
        )

    all_lines = [line for line in log_path.read_text().splitlines() if line.strip()]
    tail = all_lines[-max_records:] if max_records > 0 else []

    records: list[dict] = []
    warnings: list[str] = []
    for line in tail:
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as exc:
            warnings.append(f"skipped malformed JSON line: {exc}")
            continue
        # A line can be valid JSON and not be a record (a bare number,
        # string, or array from a truncated/partial write). Found by a
        # fresh systemic hunt 2026-08-28 after the identical class of bug
        # was found and fixed once already in check_mouth_health():
        # `.get()` on such a value crashed this function -- the central
        # consumer every sensor on the conveyor feeds through /boot --
        # so one malformed line anywhere upstream took down the whole
        # boot report, not just one check's findings.
        if not isinstance(obj, dict):
            warnings.append(f"skipped non-record JSON line (not an object): {obj!r}"[:200])
            continue
        records.append(obj)

    if not records:
        return PulseContinuity(
            available=True, latest_timestamp=None, records_considered=0,
            meaningful_findings=(),
            warnings=tuple(warnings) or ("no records in the bounded window",),
            source=source,
        )

    meaningful: list[Finding] = []
    for rec in records:
        for raw_finding in rec.get("findings", []):
            try:
                meaningful.append(Finding(**raw_finding))
            except (TypeError, ValueError) as exc:
                warnings.append(f"skipped malformed finding: {exc}")

    # Sum across the bounded window, not just the newest record: a
    # compaction that fired three ticks ago is still the most important
    # thing in this window, and reading only records[-1] would hide it.
    raw_finding_count = 0
    for rec in records:
        try:
            raw_finding_count += int(rec.get("raw_finding_count", 0))
        except (TypeError, ValueError):
            warnings.append(
                f"skipped unparseable raw_finding_count "
                f"{rec.get('raw_finding_count')!r} in one record"
            )
    compacted = any(bool(rec.get("compacted")) for rec in records)
    if compacted:
        warnings.append(
            "at least one sweep in this window was CT_141-compacted -- its "
            "findings were truncated to the highest-confidence "
            f"{COMPACTION_THRESHOLD}, so `meaningful_findings` is not the "
            "whole picture. `raw_finding_count`/`truncated_findings` say HOW "
            "MANY were dropped; the dropped findings themselves are NOT "
            "recoverable -- pulse_sweep() discards them in memory and only "
            "the truncated subset is ever written to pulse_log.jsonl. To see "
            "them, re-run pulse_sweep() directly. (Corrected 2026-08-28: this "
            "warning previously said to read pulse_log.jsonl for the rest, "
            "which was false -- the rest was never written there.)"
        )

    latest_timestamp = records[-1].get("timestamp")
    stale = False
    parsed = _parse_iso(latest_timestamp) if latest_timestamp else None
    if parsed is not None:
        from datetime import datetime, timezone
        current = now if now is not None else datetime.now(timezone.utc)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        if current.tzinfo is None:
            current = current.replace(tzinfo=timezone.utc)
        age_seconds = (current - parsed).total_seconds()
        if age_seconds > PULSE_STALE_AFTER_SECONDS:
            stale = True
            warnings.append(
                f"pulse appears stale — last observation {age_seconds / 3600:.1f}h "
                f"ago (threshold {PULSE_STALE_AFTER_SECONDS / 3600:.0f}h); the cron "
                f"pulse may have stopped running"
            )
    elif latest_timestamp:
        warnings.append(f"latest_timestamp {latest_timestamp!r} could not be parsed as ISO-8601")

    return PulseContinuity(
        available=True,
        latest_timestamp=latest_timestamp,
        records_considered=len(records),
        meaningful_findings=consolidate(meaningful),
        warnings=tuple(warnings),
        source=source,
        stale=stale,
        raw_finding_count=raw_finding_count,
        compacted=compacted,
    )


def _run_check_safely(check_fn, repo_root: Path) -> list[Finding]:
    """Isolate one check's failure from every other check and from the
    sweep itself.

    THE DEFECT THIS CLOSES (found by a fresh hunt-surface rotation
    2026-08-28, after the identical failure-physics class was already
    fixed twice this chain for JSONL readers): every check in
    `pulse_sweep()` was called bare, in sequence, with no isolation.
    Several of them call `.read_text()` on CLAUDE.md/README.md/
    PARETO_FRONTIER.md with no guard -- reproduced directly: one
    undecodable byte or one permission-denied file crashed the ENTIRE
    hourly sweep, not just the one check reading that file. Worse blast
    radius than any prior fix in this chain: a mouth-log crash lost only
    mouth-related findings; this loses every finding from every check,
    every tick, until the offending byte is fixed by a human who first
    has to notice the pulse stopped (via `read_pulse_continuity()`'s
    staleness warning) and then has to dig through `cron_pulse.err.log`
    to find out why -- exactly the two-hop diagnosis this repository's
    own conveyor exists to shortcut.

    A crashed check becomes a receipted Finding, not silence -- the same
    "never silent, always receipted" discipline `cron_pulse.py`'s own
    per-mouth isolation already uses. Observation text names only the
    check and exception TYPE (stable across ticks); the exception message
    -- which could contain a byte offset or other per-run detail --
    lives in `interpretation`, never in the dedupe key.
    """
    try:
        return check_fn(repo_root)
    except Exception as exc:  # noqa: BLE001 — a check's own failure must
        # never sink the sweep or any other check; see docstring above.
        return [Finding(
            observation=f"Level-1 check {check_fn.__name__!r} failed to run",
            evidence_location=str(repo_root),
            confidence="HIGH",
            interpretation=(
                f"{type(exc).__name__}: {exc}. This check's own findings "
                f"are unavailable this tick, but every other check still "
                f"ran -- see pulse_sweep()/_run_check_safely()'s isolation."
            ),
            reversibility="fully reversible -- observation only, nothing is rewritten",
            recommended_next_action=(
                "HUMAN_REVIEW_REQUIRED: inspect the file this check reads "
                "for encoding, permission, or corruption issues"
            ),
        )]

PROTOCOL_COMMAND_DIR = ".claude/commands"

# Only FULLY-QUALIFIED references are treated as protocol invocations.
# Two forms are in real use in this repository:
#   `foundation.sentinel.evaluate_continuation(`   (dotted module path)
#   `foundation/sigil.py::compute_sigil()`         (path::symbol)
# A bare `classify_hold()` is deliberately NOT matched -- it is prose
# shorthand for a qualified reference given elsewhere in the same step,
# and matching it would guess at a module rather than resolve one.
_PROTOCOL_DOTTED_REF = re.compile(r"\bfoundation\.((?:\w+\.)*)(\w+)\(")
_PROTOCOL_PATH_REF = re.compile(r"\bfoundation/([\w/]+)\.py::(\w+)\(")


def check_protocol_document_targets(repo_root: Path) -> list[Finding]:
    """Clause 2 of the Consumer-Reality Contract: every callable a
    protocol document names must resolve to a real definition.

    THE DEFECT THIS CLOSES (reproduced 2026-08-28, cycle demonblade_010):
    `.claude/commands/boot.md` documents nine qualified calls into
    `foundation/`. Six of those functions have NO code caller at all --
    a documented protocol step is their only consumer, which
    `PARETO_FRONTIER.md` FRONTIER-016 settled as a real form of
    consumption. But the mutation replay showed the floor was missing:
    replacing a documented function name with a typo left the ENTIRE
    test suite green. Nothing in this repository noticed that a protocol
    step pointed at a function which does not exist. A reader following
    the step would hit AttributeError on a document the repo presents as
    verified.

    This closes clause 2 and ONLY clause 2. Clause 1 (is the document
    reachable), clause 3 (does the documented invocation execute),
    clause 4 (is outcome handling stated) and clause 5 (is the ceiling
    stated) are NOT checked here -- see FRONTIER-016's own recorded
    ceiling. Resolving a name is not proving the call works.

    Read-only. Emits one Finding per unresolved reference. Volatile
    values are kept out of `observation` so `Finding.key()` stays stable
    across sweeps -- a persisting broken reference must not spam /boot
    with a new key every hour (the exact defect found in
    `check_readme_test_count` earlier this same chain).
    """
    command_dir = repo_root / PROTOCOL_COMMAND_DIR
    if not command_dir.is_dir():
        return []

    findings: list[Finding] = []
    for doc in sorted(command_dir.glob("*.md")):
        try:
            text = doc.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        rel = f"{PROTOCOL_COMMAND_DIR}/{doc.name}"

        refs: list[tuple[str, Path, str]] = []
        for match in _PROTOCOL_DOTTED_REF.finditer(text):
            prefix, name = match.group(1), match.group(2)
            if not prefix:
                # `foundation.something(` names no module -- not a
                # module-qualified call, so out of this check's scope.
                continue
            module = repo_root / "foundation" / (prefix.replace(".", "/").rstrip("/") + ".py")
            refs.append((f"foundation.{prefix}{name}()", module, name))
        for match in _PROTOCOL_PATH_REF.finditer(text):
            path, name = match.group(1), match.group(2)
            module = repo_root / "foundation" / f"{path}.py"
            refs.append((f"foundation/{path}.py::{name}()", module, name))

        for qualified, module, name in refs:
            if not module.exists():
                reason = "the module file does not exist"
            else:
                try:
                    source = module.read_text()
                except (OSError, UnicodeDecodeError):
                    continue
                defined = re.search(
                    rf"^(?:async +)?(?:def|class) +{re.escape(name)}\b",
                    source, re.MULTILINE,
                )
                if defined:
                    continue
                reason = "the module exists but defines no such name"
            findings.append(Finding(
                observation=(
                    f"{rel} documents {qualified} but that target does not "
                    f"resolve"
                ),
                evidence_location=f"{rel} -> {module}",
                confidence="HIGH",
                interpretation=(
                    f"a protocol step names this callable, and {reason}. "
                    f"Per PARETO_FRONTIER.md FRONTIER-016, a documented "
                    f"protocol step is a real consumer only if its target "
                    f"is real; an unresolvable target makes the step a "
                    f"dead reference, and a session following it would "
                    f"fail. This check resolves the NAME only -- it does "
                    f"not prove the documented call executes."
                ),
                reversibility=(
                    "fully reversible -- observation only, no document or "
                    "module is rewritten"
                ),
                recommended_next_action=(
                    "HUMAN_REVIEW_REQUIRED: correct the protocol document to "
                    "name the real callable, or restore the removed "
                    "definition"
                ),
            ))
    return findings


_LEVEL1_CHECKS: tuple = (
    check_claude_md_imports, check_subsystem_build_reports, check_python_syntax,
    check_duplicate_frontier_ids, check_frontier_schema, check_mouth_health,
    check_readme_test_count, check_sigil_snapshot_agreement,
    check_frontier_hash_placeholders, check_protocol_document_targets,
)


def pulse_sweep(repo_root: Path) -> HealthReport:
    """Run every Level-1 deterministic check and return a consolidated,
    CT_141-compacted HealthReport. Read-only: touches nothing on disk.

    Each check runs isolated via `_run_check_safely()` -- one check's
    crash must never prevent any other check, or the sweep itself, from
    completing and producing a receipt."""
    raw: list[Finding] = []
    for check_fn in _LEVEL1_CHECKS:
        raw.extend(_run_check_safely(check_fn, repo_root))

    consolidated = consolidate(raw)
    raw_count = len(consolidated)

    if raw_count > COMPACTION_THRESHOLD:
        # CT_141: overwhelm is answered by reducing scope, not by
        # generating more unverified work — keep only the highest-
        # confidence findings, in original order.
        order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        compacted_findings = tuple(
            sorted(consolidated, key=lambda f: order[f.confidence])[:COMPACTION_THRESHOLD]
        )
        return HealthReport(findings=compacted_findings, raw_finding_count=raw_count, compacted=True)

    return HealthReport(findings=consolidated, raw_finding_count=raw_count, compacted=False)


@dataclass(frozen=True)
class PathProposal:
    """One of the Four Paths' bounded output structure. Never fabricated —
    absence (None) is the honest alternative, not a filled-in guess."""

    name: str
    purpose: str
    why_now: str
    expected_benefit: str
    cost: str
    evidence: str
    scope: str
    success_criteria: str
    stop_condition: str


@dataclass(frozen=True)
class FourPaths:
    lever: Optional[PathProposal]
    foundation: Optional[PathProposal]
    reality: Optional[PathProposal]
    compaction: Optional[PathProposal]
    recommended: Optional[str] = None  # one of "LEVER"/"FOUNDATION"/"REALITY"/"COMPACTION"
    why_this_one: str = ""

    def __post_init__(self) -> None:
        if self.recommended is not None:
            slot = {
                "LEVER": self.lever, "FOUNDATION": self.foundation,
                "REALITY": self.reality, "COMPACTION": self.compaction,
            }[self.recommended]
            if slot is None:
                raise ValueError(
                    f"cannot recommend {self.recommended!r} — that path has "
                    f"no proposal (would be recommending fabricated work)"
                )


def format_four_paths(paths: FourPaths) -> str:
    """Render the exact end-of-cycle output block the source directive requires."""
    def render(label: str, proposal: Optional[PathProposal]) -> str:
        if proposal is None:
            return f"PATH {label}\nNO STRONG PATH IDENTIFIED\n"
        return (
            f"PATH {label}\n{proposal.purpose}\n\n"
            f"WHY:\n{proposal.why_now}\n"
        )

    lines = [
        "=" * 78,
        "FOUR PATHS OF EVOLUTION",
        "=" * 78,
        "",
        render("1 — LEVER", paths.lever),
        render("2 — FOUNDATION", paths.foundation),
        render("3 — REALITY", paths.reality),
        render("4 — COMPACTION", paths.compaction),
        "RECOMMENDED NEXT MOVE:",
        f"    {paths.recommended or 'NONE'}",
        "",
        "WHY THIS ONE:",
        f"    {paths.why_this_one or 'n/a'}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HOLD classification
#
# WHY THIS EXISTS
#
# Every GO-cycle doctrine file in this repository ends a cycle with a bare
# "GO / HOLD / HUMAN DECISION" line (`.claude/commands/boot.md` step 10,
# `TITANOS_NEXT_LEVER_SEQUENCER.md`'s required output tail). "HOLD" alone
# does not say WHY — a 2026-08-27 recon (see HUMAN_DECISIONS.md) found this
# repository genuinely could not distinguish "the world has no new input"
# from "the system has no mechanism to look for new input" from its own
# reports, because nothing computed the distinction; every HOLD looked the
# same. This is that missing distinction, and nothing more — a pure
# classifier, not a scheduler, not a search trigger, not a second Sentinel.
#
# WHAT THIS DOES NOT DO
#
# `classify_hold()` never decides to search, build, or recurse — it only
# names which kind of HOLD the caller is already in, from facts the caller
# already knows. Same "Finding does not equal authorization" boundary as
# the rest of this module: a HOLD_CLASS is a label for a report, not a
# trigger for `foundation.discovery_authorization.authorize_discovery()`
# or anything else.

HOLD_CLASSES = frozenset({
    "TERMINAL_HOLD", "BLOCKED_HOLD", "INPUT_STARVED_HOLD",
    "BUDGET_HOLD", "AUTHORITY_HOLD", "SIGNAL_WAIT_HOLD",
})


def classify_hold(
    *,
    has_concrete_objective: bool,
    internal_levers_exhausted: bool,
    discovery_authorized: bool = False,
    budget_exhausted: bool = False,
    authority_required: bool = False,
    blocked_reason: str = "",
    awaiting_external_signal: bool = False,
) -> str:
    """Return one member of HOLD_CLASSES from facts the caller already
    knows — pure function, no I/O, deterministic. Precedence (checked in
    this order, first match wins, mirroring the Master Constitution's own
    ordering — authority and budget are harder stops than input state):

    1. AUTHORITY_HOLD — the next action needs a human decision regardless
       of what input exists (`authority_required=True`).
    2. BUDGET_HOLD — a declared resource/discovery budget is exhausted.
    3. BLOCKED_HOLD — a precise named blocker exists (`blocked_reason`
       non-empty) that no amount of discovery would resolve on its own
       (e.g. a dependency, a decision, a missing credential).
    4. SIGNAL_WAIT_HOLD — `awaiting_external_signal=True`: a lawful public
       channel is already open (e.g. the "Bring a bottleneck" issue
       template) and the only missing element is a qualifying external
       signal (an issue, a PR, or another authorised event through that
       channel) arriving through it. Distinct from both neighbors it
       would otherwise be misreported as: not TERMINAL_HOLD (something
       IS being sought — engagement), and not INPUT_STARVED_HOLD.

       **Corrected 2026-08-28 — the original justification for that last
       distinction was factually wrong.** It read: "nothing here is a
       fetchable fact `authorize_discovery()` could go get." That is
       false, and was verified false by actually going and getting it:
       `gh issue list --repo kyle4814/titanos --state all` and
       `gh repo view ... --json issues,stargazerCount,forkCount` both
       return real data over a public, unauthenticated, READ_API path —
       squarely inside Kyle's standing discovery authorization (public
       source, no login, no credentials). The channel's state is
       eminently fetchable. Real values, 2026-08-28: 0 issues, 0 PRs,
       0 stars, 0 forks, 0 watchers.

       The class is still correct; only the reason was wrong. The real
       distinction is about what exists in the world, not what can be
       reached:

         INPUT_STARVED_HOLD — an external FACT exists that would resolve
           the objective, and we have no authorized way to reach it.
         SIGNAL_WAIT_HOLD — no external fact exists yet. We are waiting
           for another PARTY TO ACT. Fetching would faithfully report
           "still nothing," which is already the assumed state, so the
           fetch buys no information.

       This correction is load-bearing rather than pedantic: a future
       session reading "not fetchable" would conclude the public channel
       cannot be observed at all, and might therefore never build the
       observation once traffic actually justifies one. It can be
       observed. It is not worth observing yet, which is a different and
       revisable claim. The event that changes it is the first real
       inbound signal — at which point one more entry in
       `cron_pulse.MOUTHS` (the existing "one clock, many mouths, one
       loop" pattern, already proven twice) is the earned move, not a
       new mechanism.

       Added 2026-08-27 after this exact condition was
       described, without ever invoking this function, as ad hoc prose
       ("HOLD_SIGNAL_WAIT", "AWAITING_REAL_SIGNAL") across two prior
       cycles — that is weaker evidence than "the deployed classifier
       was called and returned the wrong label" and is stated honestly
       as such, but it's still real evidence the concept was needed and
       had no home. Like every other call, this is re-derived fresh
       from the caller's current facts each time — there is no stored
       state, so SIGNAL_WAIT_HOLD cannot silently persist past the
       point where the awaited signal actually arrives or another
       blocker becomes the real one; the exit condition is simply
       calling this function again with updated facts.
    5. TERMINAL_HOLD — `has_concrete_objective=False`: there is no
       unresolved objective or residue driving further work. Nothing is
       missing because nothing is being sought.
    6. INPUT_STARVED_HOLD — a concrete objective exists, internal levers
       are exhausted, but `discovery_authorized=False`: the system knows
       what it wants and cannot get it, and has no authorized way to look
       outside itself. This is the one this recon was built to name.
    7. Otherwise (`internal_levers_exhausted=False`): not actually a HOLD
       by this function's own contract — raises ValueError rather than
       inventing a label, since a caller in this state should still be
       working, not reporting a HOLD.
    """
    if authority_required:
        return "AUTHORITY_HOLD"
    if budget_exhausted:
        return "BUDGET_HOLD"
    if blocked_reason.strip():
        return "BLOCKED_HOLD"
    if awaiting_external_signal:
        return "SIGNAL_WAIT_HOLD"
    if not has_concrete_objective:
        return "TERMINAL_HOLD"
    if not internal_levers_exhausted:
        raise ValueError(
            "internal_levers_exhausted=False with a concrete objective "
            "and no blocker/budget/authority stop — this is not a HOLD "
            "state; classify_hold() will not fabricate a label for work "
            "that has not actually stalled"
        )
    if discovery_authorized:
        raise ValueError(
            "discovery_authorized=True with levers exhausted and a "
            "concrete objective is not a HOLD state either — this is the "
            "trigger condition for a bounded discovery attempt, not a "
            "reason to stop; classify_hold() only names HOLD states"
        )
    return "INPUT_STARVED_HOLD"


# --------------------------------------------------------------------------
# THE ONE LIVE PROCESS'S FAILURE RECEIPT
#
# THE EXACT OPEN EDGE THIS CLOSES (traced and reproduced 2026-08-28):
# this repository's single live crontab entry is
#
#     7 * * * * cd <repo> && /usr/bin/python3 foundation/cron_pulse.py \
#               >> <repo>/foundation/cron_pulse.err.log 2>&1
#
# The `2>&1` redirect makes `cron_pulse.err.log` a real, live failure
# producer -- it is the ONLY place a traceback goes if the one unattended
# process this repository has dies. `cron_pulse.py` prints nothing on the
# happy path, so any content in that file is failure evidence by
# construction.
#
# A grep across every `.py` and `.md` in this repository found ZERO
# readers of it. The consequence is a real, specific split: if the pulse
# dies at import (a syntax error, a missing module, a Python upgrade),
# `read_pulse_continuity()` correctly reports `stale=True` with "the cron
# pulse may have stopped running" -- detection works -- while the actual
# reason sits in a file nothing looks at. The machine could see THAT it
# stopped and never WHY.
#
# This is the precondition for any future automated repair, and it is
# deliberately NOT one: no invocation, no escalation, no retry, no
# classification of the error's meaning. It only makes an already-written
# receipt retrievable, which is the thing that must exist before anything
# smarter could ever be safe.
#
# Three states that currently collapse, and are separated here:
#   absent  -> no redirect has ever been configured (a fresh clone)
#   empty   -> the redirect exists and the process has never failed (the
#              normal, healthy state on this machine today)
#   content -> real failure output, retrievable
# --------------------------------------------------------------------------

# Bounded by BYTES, not lines: a crash-looping process appending a
# traceback every hour makes this file grow without limit, and a boot
# sequence must never read an unbounded file into memory.
CRON_STDERR_TAIL_BYTES = 8192


@dataclass(frozen=True)
class CronStderrReport:
    """Read-only view of the live cron entry's stderr capture.

    `failed` is True iff the file exists AND has content -- because
    `cron_pulse.py` writes nothing to stdout or stderr on success, any
    content at all is evidence of a real failure. `available=False`
    (absent file) is NOT a failure: it means no redirect has ever been
    configured here, which is the correct state of a fresh clone.

    Content is evidence for a human or a future session to read. This
    module never classifies what the error means, never retries, and
    never routes it anywhere -- same `finding != authorization` rule as
    every other primitive here.
    """

    available: bool
    failed: bool
    size_bytes: int
    tail: str
    truncated: bool
    warnings: tuple[str, ...]
    source: str


def read_cron_stderr(
    repo_root: Path,
    tail_bytes: int = CRON_STDERR_TAIL_BYTES,
) -> CronStderrReport:
    """Retrieve the tail of `foundation/cron_pulse.err.log`.

    Read-only -- never writes, truncates, or rotates the file (rotation
    is a real future question, but truncating the only evidence of a
    failure while reading it would be exactly backwards). Bounded to the
    trailing `tail_bytes`. Fails soft: an unreadable file is reported as
    a warning, never raised, so a boot sequence cannot be broken by a
    permissions problem on a log.
    """
    log_path = repo_root / "foundation" / "cron_pulse.err.log"
    source = str(log_path)

    if not log_path.exists():
        return CronStderrReport(
            available=False, failed=False, size_bytes=0, tail="", truncated=False,
            warnings=(
                "cron_pulse.err.log does not exist -- no stderr redirect has "
                "ever been configured here (the correct state of a fresh "
                "clone, not a fault, and not evidence that the pulse is healthy)",
            ),
            source=source,
        )

    try:
        size = log_path.stat().st_size
    except OSError as exc:
        return CronStderrReport(
            available=False, failed=False, size_bytes=0, tail="", truncated=False,
            warnings=(f"could not stat cron_pulse.err.log: {exc}",), source=source,
        )

    if size == 0:
        return CronStderrReport(
            available=True, failed=False, size_bytes=0, tail="", truncated=False,
            warnings=(), source=source,
        )

    warnings: list[str] = []
    truncated = size > tail_bytes
    try:
        with open(log_path, "rb") as fh:
            if truncated:
                fh.seek(-tail_bytes, 2)
            raw = fh.read()
        tail = raw.decode("utf-8", errors="replace")
    except OSError as exc:
        return CronStderrReport(
            available=True, failed=True, size_bytes=size, tail="", truncated=False,
            warnings=(f"cron_pulse.err.log has content but could not be read: {exc}",),
            source=source,
        )

    if truncated:
        warnings.append(
            f"cron_pulse.err.log is {size} bytes; showing the trailing "
            f"{tail_bytes} only -- read the file directly for the rest"
        )
    warnings.append(
        "cron_pulse.py produces no output on success, so any content here "
        "is real failure evidence from the one unattended process this "
        "repository runs -- this is retrieval, not a diagnosis"
    )

    return CronStderrReport(
        available=True, failed=True, size_bytes=size, tail=tail,
        truncated=truncated, warnings=tuple(warnings), source=source,
    )
