"""
Sentinel_141 — Level 1 Pulse Sweep + Four Paths Protocol
(TITANOS_SENTINEL_141.md, "Continuous Repository Observation + Four Paths").

WHAT THIS FILE IS, AND IS NOT

A sensor, not a second autonomous builder. Every function in this module
is read-only with respect to the repository: it inspects files and
returns data. **Nothing here writes, deletes, builds, or executes** —
that boundary is a structural fact, not a documented promise, and
`TestSentinelCannotExecute` below checks it by enumerating this module's
public callables.

WHAT WAS AUDITED BEFORE BUILDING

No monitoring, queue producer, health-report generator, or scheduled
sweep exists anywhere in this repository — `PARETO_FRONTIER.md`/
`NEXT_MOVE.md`/`BUILD_REPORT.md` are all hand-maintained prose, updated
manually each cycle, never generated by a deterministic check. No
scheduler exists (no GitHub remote — same standing fact as
`PARETO_FRONTIER.md` FRONTIER-003), so this module implements only
Level 1 (Pulse Sweep) — deterministic, cheap, no model-based review —
and leaves Level 2 (Deep Sweep, semantic) and Level 3 (Strategic
Compaction Review) as doctrine, not code, per the source directive's own
"use model-based review only for semantic questions deterministic code
cannot answer" instruction. Building Level 2/3 as code now, with no
Level 1 in production use yet to prove the pattern, would be exactly the
"busiest system" the source directive's own Final Doctrine warns
against.

WHY THE CHECKS CHOSEN ARE THE ONES CHOSEN

Each of the four `check_*` functions below was picked because running it
against the real repository (not a synthetic fixture) found something
true: `check_claude_md_imports` confirms every `@`-import target exists
(currently: yes); `check_subsystem_build_reports` finds three real
subsystems (`schema/`, `firewall/`, `narrative/`) with no `BUILD_REPORT.md`
at all, unlike their five siblings; `check_python_syntax` is a zero-cost
correctness net; `check_duplicate_frontier_ids` guards the one append-only
registry (`PARETO_FRONTIER.md`) this repo already relies on humans to
keep internally consistent by hand.

CT_141 COMPACTION

`pulse_sweep()` applies the source directive's CT_141 rule directly: if
raw finding count exceeds `COMPACTION_THRESHOLD`, the report is
compacted into a summary (`compacted=True`, `findings` truncated to the
highest-confidence subset) rather than dumping every finding — "never
respond to overwhelm by generating more unverified work."
"""

from __future__ import annotations

import ast
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

__all__ = [
    "Finding",
    "HealthReport",
    "PathProposal",
    "FourPaths",
    "pulse_sweep",
    "consolidate",
    "format_four_paths",
    "PulseContinuity",
    "read_pulse_continuity",
    "PULSE_LOG_MAX_RECORDS",
    "SUBSYSTEMS_REQUIRING_BUILD_REPORT",
    "COMPACTION_THRESHOLD",
    "HOLD_CLASSES",
    "classify_hold",
    "check_mouth_health",
    "LIVE_MOUTH_IDS",
]

CONFIDENCE_VALUES = frozenset({"HIGH", "MEDIUM", "LOW"})

# Subsystems this repo's own doctrine (CLAUDE.md "Standing facts") names
# as requiring a BUILD_REPORT.md. Fixed list, not auto-discovered — a
# directory becomes a "subsystem" by human decision, not by having a
# tests/ folder, so this check does not try to infer that decision.
SUBSYSTEMS_REQUIRING_BUILD_REPORT: tuple[str, ...] = (
    "schema", "firewall", "kpm", "magl", "rpa", "taal", "foundation", "narrative",
)

# CT_141: above this many raw findings in one sweep, compact rather than
# dump — deliberately small, this is a Level 1 sweep, not an incident report.
COMPACTION_THRESHOLD = 20

_EXCLUDED_DIRS = {".git", "__pycache__", "node_modules"}


@dataclass(frozen=True)
class Finding:
    """One Level-1 observation. `finding does not equal authorization` —
    nothing about a Finding's shape implies permission to act on it."""

    observation: str
    evidence_location: str
    confidence: str
    interpretation: str
    reversibility: str
    recommended_next_action: str

    def __post_init__(self) -> None:
        if self.confidence not in CONFIDENCE_VALUES:
            raise ValueError(
                f"confidence {self.confidence!r} must be one of {sorted(CONFIDENCE_VALUES)}"
            )
        if not self.evidence_location:
            raise ValueError(
                "a Finding requires evidence_location — a finding with no "
                "location is an opinion, not an observation."
            )

    def key(self) -> tuple[str, str]:
        """Identity used for deduplication: same observation at same location."""
        return (self.observation, self.evidence_location)


@dataclass(frozen=True)
class HealthReport:
    findings: tuple[Finding, ...]
    raw_finding_count: int
    compacted: bool


def consolidate(findings: list[Finding]) -> tuple[Finding, ...]:
    """Deduplicate findings sharing (observation, evidence_location).

    First occurrence wins — later duplicates carry no new location, so
    there is nothing to merge beyond dropping the repeat.
    """
    seen: dict[tuple[str, str], Finding] = {}
    for f in findings:
        seen.setdefault(f.key(), f)
    return tuple(seen.values())


def check_claude_md_imports(repo_root: Path) -> list[Finding]:
    claude_md = repo_root / "CLAUDE.md"
    if not claude_md.exists():
        return [Finding(
            observation="CLAUDE.md is missing",
            evidence_location=str(claude_md),
            confidence="HIGH",
            interpretation="boot configuration is entirely absent",
            reversibility="reversible — file can be restored from git history",
            recommended_next_action="HUMAN_REVIEW_REQUIRED",
        )]
    findings: list[Finding] = []
    for line in claude_md.read_text().splitlines():
        line = line.strip()
        if not line.startswith("@"):
            continue
        target = repo_root / line[1:]
        if not target.exists():
            findings.append(Finding(
                observation=f"CLAUDE.md @-imports a missing file: {line}",
                evidence_location=str(claude_md),
                confidence="HIGH",
                interpretation="doctrine index references a file that does not exist",
                reversibility="reversible — fix the reference or restore the file",
                recommended_next_action="DEFERRED_WITH_NEXT_ACTION: verify and repair the import",
            ))
    return findings


def check_subsystem_build_reports(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for name in SUBSYSTEMS_REQUIRING_BUILD_REPORT:
        subsystem_dir = repo_root / name
        if not subsystem_dir.is_dir():
            continue
        if not (subsystem_dir / "BUILD_REPORT.md").exists():
            findings.append(Finding(
                observation=f"subsystem '{name}' has no BUILD_REPORT.md",
                evidence_location=str(subsystem_dir),
                confidence="MEDIUM",
                interpretation=(
                    "every sibling subsystem carries a BUILD_REPORT.md with "
                    "limitations/human-decisions/next-work-cell sections; "
                    "this one does not, which may mean the audit trail for "
                    "this subsystem lives only in commit messages"
                ),
                reversibility="fully reversible — adding a document has no side effects",
                recommended_next_action="candidate for PARETO_FRONTIER.md, not auto-created",
            ))
    return findings


def check_python_syntax(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in repo_root.rglob("*.py"):
        if any(part in _EXCLUDED_DIRS for part in path.parts):
            continue
        try:
            ast.parse(path.read_text(), filename=str(path))
        except SyntaxError as exc:
            findings.append(Finding(
                observation=f"syntax error: {exc.msg}",
                evidence_location=f"{path}:{exc.lineno}",
                confidence="HIGH",
                interpretation="file cannot be parsed by Python",
                reversibility="reversible — a syntax error blocks nothing until imported",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
    return findings


def check_duplicate_frontier_ids(repo_root: Path) -> list[Finding]:
    frontier_md = repo_root / "PARETO_FRONTIER.md"
    if not frontier_md.exists():
        return []
    ids = re.findall(r"^### (FRONTIER-\S+)", frontier_md.read_text(), flags=re.MULTILINE)
    seen: set[str] = set()
    findings: list[Finding] = []
    for frontier_id in ids:
        if frontier_id in seen:
            findings.append(Finding(
                observation=f"duplicate frontier id: {frontier_id}",
                evidence_location=str(frontier_md),
                confidence="HIGH",
                interpretation="the same candidate id was used twice, risking confused status tracking",
                reversibility="reversible — rename one entry",
                recommended_next_action="HUMAN_REVIEW_REQUIRED",
            ))
        seen.add(frontier_id)
    return findings


# `## Active` and `## Blocked` entries are checked for the one field
# pair genuinely present in 100% of real entries at time of writing
# (verified by reading the file, not assumed) — `- **CURRENT:**` and
# `- **GAP:**`, always as the entry's first two bullets. `## Archive`
# (a one-line table, different shape entirely) and `## Rejected` are
# not checked — this validator verifies declared structure is
# complete, per section, for the shape that section actually uses; it
# does not impose one schema on every section. It never judges whether
# an entry's content is strategically correct — only that the two
# always-present structural fields exist (`MARKDOWN_EXECUTION_
# BOUNDARY_001`'s own Anti-Overreach Law: structural validity != strategic truth).
_FRONTIER_ENTRY_SECTIONS = ("## Active", "## Blocked")



# THE BLIND SPOT THIS CLOSES (reproduced 2026-08-28 before building):
# `cron_pulse.py` writes an `UNAVAILABLE` record whenever a mouth's fetch
# fails, and that per-mouth try/except is deliberate -- one mouth's
# failure must never sink the tick. But nothing ever converted those
# records into a Finding, so the hourly sweep reported
# `raw_finding_count=0` -- indistinguishable from perfect health -- while
# a mouth had failed five consecutive times. Directly reproduced: five
# UNAVAILABLE records in a row produced zero mouth-related findings.
#
# That is the worst shape a monitoring failure can take: silent loss of
# the organism's only sensory organs, reported as health. Every other
# check in this module inspects the repository as a set of documents;
# this is the first that inspects whether the live sensing apparatus is
# still working. That is a genuinely new information channel, not a
# second name for something already reported.
#
# WHY TWO CONSECUTIVE FAILURES, NOT ONE: a single failed fetch is normal
# variation for network I/O -- PyPI and GitHub will occasionally 503,
# rate-limit, or lose a DNS lookup, and a blip that recovers on the next
# tick is the system working as designed (prior state is preserved
# untouched). Requiring the two most recent observations to BOTH be
# UNAVAILABLE is what separates a real persistent failure from weather.
# This is the "distinguish transient from repeated" distinction that was
# correctly killed twice in earlier cycles for having no consumer; it is
# earned now only because `Finding` -> `pulse_log.jsonl` ->
# `read_pulse_continuity()` -> `/boot` was subsequently proven complete
# end to end.
#
# The observation text is deliberately STABLE -- no counts, no
# timestamps -- so `Finding.key()` collapses a persistent failure to one
# finding for as long as it lasts, and it disappears by itself on the
# first successful fetch. A streak counter in the text would change the
# key every tick and spam the boot report, which is the exact failure
# this repository's dedupe discipline exists to prevent.
#
# Fixed list, not a glob, for the same reason
# SUBSYSTEMS_REQUIRING_BUILD_REPORT is fixed: `foundation/` still
# contains `mouth_pypi_log.jsonl`, an orphan from an earlier MOUTH_ID
# naming that nothing writes any more. A glob would report it stale
# forever with no remedy but deletion -- a static fact re-reported
# eternally, which is a kill criterion, not a finding.
LIVE_MOUTH_IDS: tuple[str, ...] = ("pypi_pyyaml_releases", "github_pyyaml_releases")


def check_mouth_health(repo_root: Path, now: Optional["datetime"] = None) -> list[Finding]:
    """Convert persistent mouth failure or a stopped mouth clock into
    Findings. Read-only, bounded (at most LOG_MAX_RECORDS lines per
    mouth, two mouths), fail-soft on malformed lines.

    A missing log is NOT a finding: on a fresh clone the mouths have
    simply never run, which is the correct initial state."""
    from foundation.mouth_common import LOG_MAX_RECORDS, LOG_STALE_AFTER_SECONDS

    findings: list[Finding] = []
    for mouth_id in LIVE_MOUTH_IDS:
        log_path = repo_root / "foundation" / f"mouth_{mouth_id}_log.jsonl"
        if not log_path.exists():
            continue
        try:
            lines = [l for l in log_path.read_text(encoding="utf-8").splitlines() if l.strip()]
        except OSError:
            continue

        records = []
        for line in lines[-LOG_MAX_RECORDS:]:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            # A line can be valid JSON and still not be a record (a bare
            # number or string from a truncated/partial write). Found by
            # adversarial review 2026-08-28: `.get()` on such a value raised
            # AttributeError out of this check and out of pulse_sweep(),
            # taking down EVERY other check's findings with it -- one
            # malformed byte disabling the whole hourly sweep.
            if not isinstance(obj, dict):
                continue
            records.append(obj)
        if not records:
            continue

        recent = records[-2:]
        if len(recent) == 2 and all(r.get("status") == "UNAVAILABLE" for r in recent):
            findings.append(Finding(
                observation=(
                    f"mouth {mouth_id!r} failed its two most recent observations "
                    f"-- persistent fetch failure, not a transient blip"
                ),
                evidence_location=str(log_path),
                confidence="HIGH",
                interpretation=(
                    "this repository's only sensory organs are its two mouths. "
                    "A persistently failing mouth means external change is no "
                    "longer being observed at all, while the pulse otherwise "
                    "reports normally -- silent sensory loss. Prior state is "
                    "preserved untouched by design, so nothing is corrupted; "
                    "the cost is blindness, not damage. Most recent error: "
                    + str(records[-1].get("error", "not recorded"))[:200]
                ),
                reversibility=(
                    "fully reversible -- observation only; the finding clears "
                    "itself on the first successful fetch"
                ),
                recommended_next_action=(
                    "HUMAN_REVIEW_REQUIRED: check network reachability and "
                    "whether the feed URL still resolves"
                ),
            ))
            continue

        latest_ts = records[-1].get("observed_at") or records[-1].get("timestamp")
        parsed = _parse_iso(latest_ts) if latest_ts else None
        if parsed is None:
            continue
        from datetime import datetime as _dt, timezone as _tz
        current = now if now is not None else _dt.now(_tz.utc)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=_tz.utc)
        if current.tzinfo is None:
            current = current.replace(tzinfo=_tz.utc)
        if (current - parsed).total_seconds() > LOG_STALE_AFTER_SECONDS:
            findings.append(Finding(
                observation=(
                    f"mouth {mouth_id!r} has stopped writing observations "
                    f"(newest record older than the staleness threshold)"
                ),
                evidence_location=str(log_path),
                confidence="MEDIUM",
                interpretation=(
                    "the mouth is not failing -- it is not running at all. "
                    "Distinct from a fetch failure: no UNAVAILABLE records are "
                    "being written either, which points at the clock (the cron "
                    "entry) rather than the network. See "
                    "foundation/cron_pulse.err.log via read_cron_stderr()."
                ),
                reversibility="fully reversible -- observation only",
                recommended_next_action=(
                    "HUMAN_REVIEW_REQUIRED: confirm the cron entry is still "
                    "installed and check cron_pulse.err.log"
                ),
            ))
    return findings

def check_frontier_schema(repo_root: Path) -> list[Finding]:
    frontier_md = repo_root / "PARETO_FRONTIER.md"
    if not frontier_md.exists():
        return []
    text = frontier_md.read_text()
    lines = text.splitlines()

    findings: list[Finding] = []
    current_section: str | None = None
    current_entry_id: str | None = None
    entry_lines: list[str] = []

    def _check_entry(entry_id: str, body_lines: list[str]) -> None:
        body = "\n".join(body_lines)
        for field_name in ("- **CURRENT:**", "- **GAP:**"):
            if field_name not in body:
                findings.append(Finding(
                    observation=f"{entry_id} is missing required field {field_name}",
                    evidence_location=f"{frontier_md}::{entry_id}",
                    confidence="HIGH",
                    interpretation=(
                        "every Active/Blocked entry has carried CURRENT and GAP "
                        "as its first two bullets in this file's real history; "
                        "this entry does not"
                    ),
                    reversibility="reversible — add the missing bullet",
                    recommended_next_action="review if publishing",
                ))

    for line in lines:
        if line.startswith("## "):
            if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
                _check_entry(current_entry_id, entry_lines)
            current_section = line.strip()
            current_entry_id = None
            entry_lines = []
            continue
        if line.startswith("### FRONTIER"):
            if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
                _check_entry(current_entry_id, entry_lines)
            match = re.match(r"### (FRONTIER-\S+)", line)
            current_entry_id = match.group(1) if match else line.strip()
            entry_lines = []
            continue
        entry_lines.append(line)

    if current_entry_id and current_section in _FRONTIER_ENTRY_SECTIONS:
        _check_entry(current_entry_id, entry_lines)

    return findings


PULSE_LOG_MAX_RECORDS = 20

# cron_pulse.py is scheduled hourly (see the crontab entry it was
# installed with). 3x the expected interval is stale enough to mean
# "the clock likely stopped," not "it just hasn't ticked yet this hour."
PULSE_EXPECTED_INTERVAL_SECONDS = 3600
PULSE_STALE_AFTER_SECONDS = 3 * PULSE_EXPECTED_INTERVAL_SECONDS


@dataclass(frozen=True)
class PulseContinuity:
    """Bounded, read-only view of what `foundation/cron_pulse.py` observed
    while nobody was in a session. Boot-time answer to "what happened
    while the clock was running alone" — never more than that. A
    non-empty `meaningful_findings` is evidence to look at, not something
    already authorized to act on (same `finding != authorization` rule
    as every other Finding in this module).

    `stale=True` means the latest record is older than
    `PULSE_STALE_AFTER_SECONDS` — the clock may have stopped running.
    `stale=False` on an empty/unavailable log is not a health claim
    (there is nothing to be stale); check `available` first.
    """

    available: bool
    latest_timestamp: Optional[str]
    records_considered: int
    meaningful_findings: tuple[Finding, ...]
    warnings: tuple[str, ...]
    source: str
    stale: bool = False


def _parse_iso(ts: str) -> Optional["datetime"]:
    from datetime import datetime
    try:
        return datetime.fromisoformat(ts)
    except (ValueError, TypeError):
        return None


def read_pulse_continuity(
    repo_root: Path,
    max_records: int = PULSE_LOG_MAX_RECORDS,
    now: Optional["datetime"] = None,
) -> PulseContinuity:
    """Read the tail of `foundation/pulse_log.jsonl` and summarise it.

    Read-only — never writes, truncates, or rotates the log. Bounded —
    reads at most `max_records` trailing lines regardless of file size,
    so a large log cannot flood a caller. Fails soft at every layer: a
    missing file, an empty file, and individual malformed JSON lines or
    malformed Finding payloads are all reported as `warnings`, never
    raised — a boot sequence must not fail because the heartbeat has
    never run or because one line got corrupted mid-write.
    """
    log_path = repo_root / "foundation" / "pulse_log.jsonl"
    source = str(log_path)

    if not log_path.exists():
        return PulseContinuity(
            available=False, latest_timestamp=None, records_considered=0,
            meaningful_findings=(),
            warnings=("pulse_log.jsonl does not exist yet — the cron pulse has never run",),
            source=source,
        )

    all_lines = [line for line in log_path.read_text().splitlines() if line.strip()]
    tail = all_lines[-max_records:] if max_records > 0 else []

    records: list[dict] = []
    warnings: list[str] = []
    for line in tail:
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as exc:
            warnings.append(f"skipped malformed JSON line: {exc}")
            continue
        # A line can be valid JSON and not be a record (a bare number,
        # string, or array from a truncated/partial write). Found by a
        # fresh systemic hunt 2026-08-28 after the identical class of bug
        # was found and fixed once already in check_mouth_health():
        # `.get()` on such a value crashed this function -- the central
        # consumer every sensor on the conveyor feeds through /boot --
        # so one malformed line anywhere upstream took down the whole
        # boot report, not just one check's findings.
        if not isinstance(obj, dict):
            warnings.append(f"skipped non-record JSON line (not an object): {obj!r}"[:200])
            continue
        records.append(obj)

    if not records:
        return PulseContinuity(
            available=True, latest_timestamp=None, records_considered=0,
            meaningful_findings=(),
            warnings=tuple(warnings) or ("no records in the bounded window",),
            source=source,
        )

    meaningful: list[Finding] = []
    for rec in records:
        for raw_finding in rec.get("findings", []):
            try:
                meaningful.append(Finding(**raw_finding))
            except (TypeError, ValueError) as exc:
                warnings.append(f"skipped malformed finding: {exc}")

    latest_timestamp = records[-1].get("timestamp")
    stale = False
    parsed = _parse_iso(latest_timestamp) if latest_timestamp else None
    if parsed is not None:
        from datetime import datetime, timezone
        current = now if now is not None else datetime.now(timezone.utc)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        if current.tzinfo is None:
            current = current.replace(tzinfo=timezone.utc)
        age_seconds = (current - parsed).total_seconds()
        if age_seconds > PULSE_STALE_AFTER_SECONDS:
            stale = True
            warnings.append(
                f"pulse appears stale — last observation {age_seconds / 3600:.1f}h "
                f"ago (threshold {PULSE_STALE_AFTER_SECONDS / 3600:.0f}h); the cron "
                f"pulse may have stopped running"
            )
    elif latest_timestamp:
        warnings.append(f"latest_timestamp {latest_timestamp!r} could not be parsed as ISO-8601")

    return PulseContinuity(
        available=True,
        latest_timestamp=latest_timestamp,
        records_considered=len(records),
        meaningful_findings=consolidate(meaningful),
        warnings=tuple(warnings),
        source=source,
        stale=stale,
    )


def _run_check_safely(check_fn, repo_root: Path) -> list[Finding]:
    """Isolate one check's failure from every other check and from the
    sweep itself.

    THE DEFECT THIS CLOSES (found by a fresh hunt-surface rotation
    2026-08-28, after the identical failure-physics class was already
    fixed twice this chain for JSONL readers): every check in
    `pulse_sweep()` was called bare, in sequence, with no isolation.
    Several of them call `.read_text()` on CLAUDE.md/README.md/
    PARETO_FRONTIER.md with no guard -- reproduced directly: one
    undecodable byte or one permission-denied file crashed the ENTIRE
    hourly sweep, not just the one check reading that file. Worse blast
    radius than any prior fix in this chain: a mouth-log crash lost only
    mouth-related findings; this loses every finding from every check,
    every tick, until the offending byte is fixed by a human who first
    has to notice the pulse stopped (via `read_pulse_continuity()`'s
    staleness warning) and then has to dig through `cron_pulse.err.log`
    to find out why -- exactly the two-hop diagnosis this repository's
    own conveyor exists to shortcut.

    A crashed check becomes a receipted Finding, not silence -- the same
    "never silent, always receipted" discipline `cron_pulse.py`'s own
    per-mouth isolation already uses. Observation text names only the
    check and exception TYPE (stable across ticks); the exception message
    -- which could contain a byte offset or other per-run detail --
    lives in `interpretation`, never in the dedupe key.
    """
    try:
        return check_fn(repo_root)
    except Exception as exc:  # noqa: BLE001 — a check's own failure must
        # never sink the sweep or any other check; see docstring above.
        return [Finding(
            observation=f"Level-1 check {check_fn.__name__!r} failed to run",
            evidence_location=str(repo_root),
            confidence="HIGH",
            interpretation=(
                f"{type(exc).__name__}: {exc}. This check's own findings "
                f"are unavailable this tick, but every other check still "
                f"ran -- see pulse_sweep()/_run_check_safely()'s isolation."
            ),
            reversibility="fully reversible -- observation only, nothing is rewritten",
            recommended_next_action=(
                "HUMAN_REVIEW_REQUIRED: inspect the file this check reads "
                "for encoding, permission, or corruption issues"
            ),
        )]

_LEVEL1_CHECKS: tuple = (
    check_claude_md_imports, check_subsystem_build_reports, check_python_syntax,
    check_duplicate_frontier_ids, check_frontier_schema, check_mouth_health,
)


def pulse_sweep(repo_root: Path) -> HealthReport:
    """Run every Level-1 deterministic check and return a consolidated,
    CT_141-compacted HealthReport. Read-only: touches nothing on disk.

    Each check runs isolated via `_run_check_safely()` -- one check's
    crash must never prevent any other check, or the sweep itself, from
    completing and producing a receipt."""
    raw: list[Finding] = []
    for check_fn in _LEVEL1_CHECKS:
        raw.extend(_run_check_safely(check_fn, repo_root))

    consolidated = consolidate(raw)
    raw_count = len(consolidated)

    if raw_count > COMPACTION_THRESHOLD:
        # CT_141: overwhelm is answered by reducing scope, not by
        # generating more unverified work — keep only the highest-
        # confidence findings, in original order.
        order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        compacted_findings = tuple(
            sorted(consolidated, key=lambda f: order[f.confidence])[:COMPACTION_THRESHOLD]
        )
        return HealthReport(findings=compacted_findings, raw_finding_count=raw_count, compacted=True)

    return HealthReport(findings=consolidated, raw_finding_count=raw_count, compacted=False)


@dataclass(frozen=True)
class PathProposal:
    """One of the Four Paths' bounded output structure. Never fabricated —
    absence (None) is the honest alternative, not a filled-in guess."""

    name: str
    purpose: str
    why_now: str
    expected_benefit: str
    cost: str
    evidence: str
    scope: str
    success_criteria: str
    stop_condition: str


@dataclass(frozen=True)
class FourPaths:
    lever: Optional[PathProposal]
    foundation: Optional[PathProposal]
    reality: Optional[PathProposal]
    compaction: Optional[PathProposal]
    recommended: Optional[str] = None  # one of "LEVER"/"FOUNDATION"/"REALITY"/"COMPACTION"
    why_this_one: str = ""

    def __post_init__(self) -> None:
        if self.recommended is not None:
            slot = {
                "LEVER": self.lever, "FOUNDATION": self.foundation,
                "REALITY": self.reality, "COMPACTION": self.compaction,
            }[self.recommended]
            if slot is None:
                raise ValueError(
                    f"cannot recommend {self.recommended!r} — that path has "
                    f"no proposal (would be recommending fabricated work)"
                )


def format_four_paths(paths: FourPaths) -> str:
    """Render the exact end-of-cycle output block the source directive requires."""
    def render(label: str, proposal: Optional[PathProposal]) -> str:
        if proposal is None:
            return f"PATH {label}\nNO STRONG PATH IDENTIFIED\n"
        return (
            f"PATH {label}\n{proposal.purpose}\n\n"
            f"WHY:\n{proposal.why_now}\n"
        )

    lines = [
        "=" * 78,
        "FOUR PATHS OF EVOLUTION",
        "=" * 78,
        "",
        render("1 — LEVER", paths.lever),
        render("2 — FOUNDATION", paths.foundation),
        render("3 — REALITY", paths.reality),
        render("4 — COMPACTION", paths.compaction),
        "RECOMMENDED NEXT MOVE:",
        f"    {paths.recommended or 'NONE'}",
        "",
        "WHY THIS ONE:",
        f"    {paths.why_this_one or 'n/a'}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HOLD classification
#
# WHY THIS EXISTS
#
# Every GO-cycle doctrine file in this repository ends a cycle with a bare
# "GO / HOLD / HUMAN DECISION" line (`.claude/commands/boot.md` step 10,
# `TITANOS_NEXT_LEVER_SEQUENCER.md`'s required output tail). "HOLD" alone
# does not say WHY — a 2026-08-27 recon (see HUMAN_DECISIONS.md) found this
# repository genuinely could not distinguish "the world has no new input"
# from "the system has no mechanism to look for new input" from its own
# reports, because nothing computed the distinction; every HOLD looked the
# same. This is that missing distinction, and nothing more — a pure
# classifier, not a scheduler, not a search trigger, not a second Sentinel.
#
# WHAT THIS DOES NOT DO
#
# `classify_hold()` never decides to search, build, or recurse — it only
# names which kind of HOLD the caller is already in, from facts the caller
# already knows. Same "Finding does not equal authorization" boundary as
# the rest of this module: a HOLD_CLASS is a label for a report, not a
# trigger for `foundation.discovery_authorization.authorize_discovery()`
# or anything else.

HOLD_CLASSES = frozenset({
    "TERMINAL_HOLD", "BLOCKED_HOLD", "INPUT_STARVED_HOLD",
    "BUDGET_HOLD", "AUTHORITY_HOLD", "SIGNAL_WAIT_HOLD",
})


def classify_hold(
    *,
    has_concrete_objective: bool,
    internal_levers_exhausted: bool,
    discovery_authorized: bool = False,
    budget_exhausted: bool = False,
    authority_required: bool = False,
    blocked_reason: str = "",
    awaiting_external_signal: bool = False,
) -> str:
    """Return one member of HOLD_CLASSES from facts the caller already
    knows — pure function, no I/O, deterministic. Precedence (checked in
    this order, first match wins, mirroring the Master Constitution's own
    ordering — authority and budget are harder stops than input state):

    1. AUTHORITY_HOLD — the next action needs a human decision regardless
       of what input exists (`authority_required=True`).
    2. BUDGET_HOLD — a declared resource/discovery budget is exhausted.
    3. BLOCKED_HOLD — a precise named blocker exists (`blocked_reason`
       non-empty) that no amount of discovery would resolve on its own
       (e.g. a dependency, a decision, a missing credential).
    4. SIGNAL_WAIT_HOLD — `awaiting_external_signal=True`: a lawful public
       channel is already open (e.g. the "Bring a bottleneck" issue
       template) and the only missing element is a qualifying external
       signal (an issue, a PR, or another authorised event through that
       channel) arriving through it. Distinct from both neighbors it
       would otherwise be misreported as: not TERMINAL_HOLD (something
       IS being sought — engagement), and not INPUT_STARVED_HOLD
       (nothing here is a fetchable fact `authorize_discovery()` could
       go get — waiting for a signal to arrive is not a discovery
       objective). Added 2026-08-27 after this exact condition was
       described, without ever invoking this function, as ad hoc prose
       ("HOLD_SIGNAL_WAIT", "AWAITING_REAL_SIGNAL") across two prior
       cycles — that is weaker evidence than "the deployed classifier
       was called and returned the wrong label" and is stated honestly
       as such, but it's still real evidence the concept was needed and
       had no home. Like every other call, this is re-derived fresh
       from the caller's current facts each time — there is no stored
       state, so SIGNAL_WAIT_HOLD cannot silently persist past the
       point where the awaited signal actually arrives or another
       blocker becomes the real one; the exit condition is simply
       calling this function again with updated facts.
    5. TERMINAL_HOLD — `has_concrete_objective=False`: there is no
       unresolved objective or residue driving further work. Nothing is
       missing because nothing is being sought.
    6. INPUT_STARVED_HOLD — a concrete objective exists, internal levers
       are exhausted, but `discovery_authorized=False`: the system knows
       what it wants and cannot get it, and has no authorized way to look
       outside itself. This is the one this recon was built to name.
    7. Otherwise (`internal_levers_exhausted=False`): not actually a HOLD
       by this function's own contract — raises ValueError rather than
       inventing a label, since a caller in this state should still be
       working, not reporting a HOLD.
    """
    if authority_required:
        return "AUTHORITY_HOLD"
    if budget_exhausted:
        return "BUDGET_HOLD"
    if blocked_reason.strip():
        return "BLOCKED_HOLD"
    if awaiting_external_signal:
        return "SIGNAL_WAIT_HOLD"
    if not has_concrete_objective:
        return "TERMINAL_HOLD"
    if not internal_levers_exhausted:
        raise ValueError(
            "internal_levers_exhausted=False with a concrete objective "
            "and no blocker/budget/authority stop — this is not a HOLD "
            "state; classify_hold() will not fabricate a label for work "
            "that has not actually stalled"
        )
    if discovery_authorized:
        raise ValueError(
            "discovery_authorized=True with levers exhausted and a "
            "concrete objective is not a HOLD state either — this is the "
            "trigger condition for a bounded discovery attempt, not a "
            "reason to stop; classify_hold() only names HOLD states"
        )
    return "INPUT_STARVED_HOLD"
